import Foundation

struct EmojiCategory: Identifiable {
    let id: String
    let name: String
    let icon: String
    let emojis: [EmojiItem]
}

struct EmojiItem: Identifiable {
    let id: String
    let emoji: String
    let keywords: [String]

    init(_ emoji: String, _ keywords: [String] = []) {
        self.id = emoji
        self.emoji = emoji
        self.keywords = keywords
    }
}

enum EmojiData {
    static let defaultQuickReactions = ["👍", "❤️", "😂", "😮", "😢", "🙏"]

    static let categories: [EmojiCategory] = [
        EmojiCategory(id: "recent", name: "Recent", icon: "clock", emojis: []),
        EmojiCategory(id: "smileys", name: "Smileys & People", icon: "face.smiling", emojis: smileys),
        EmojiCategory(id: "animals", name: "Animals & Nature", icon: "hare", emojis: animals),
        EmojiCategory(id: "food", name: "Food & Drink", icon: "fork.knife", emojis: food),
        EmojiCategory(id: "travel", name: "Travel & Places", icon: "car", emojis: travel),
        EmojiCategory(id: "activities", name: "Activities", icon: "sportscourt", emojis: activities),
        EmojiCategory(id: "objects", name: "Objects", icon: "lightbulb", emojis: objects),
        EmojiCategory(id: "symbols", name: "Symbols", icon: "heart", emojis: symbols),
        EmojiCategory(id: "flags", name: "Flags", icon: "flag", emojis: flags),
    ]

    static func search(_ query: String) -> [EmojiItem] {
        let q = query.lowercased()
        var seen = Set<String>()
        return categories.flatMap(\.emojis).filter { item in
            guard !seen.contains(item.emoji) else { return false }
            let matches = item.emoji.contains(q) || item.keywords.contains { $0.contains(q) }
            if matches { seen.insert(item.emoji) }
            return matches
        }
    }

    // MARK: - Smileys & People (553)
    static let smileys: [EmojiItem] = [
        EmojiItem("😀", ["grinning", "face"]),
        EmojiItem("😃", ["grinning", "face", "with", "big", "eyes"]),
        EmojiItem("😄", ["grinning", "face", "with", "smiling", "eyes"]),
        EmojiItem("😁", ["beaming", "face", "with", "smiling", "eyes"]),
        EmojiItem("😆", ["grinning", "squinting", "face"]),
        EmojiItem("😅", ["grinning", "face", "with", "sweat"]),
        EmojiItem("🤣", ["rolling", "on", "the", "floor", "laughing"]),
        EmojiItem("😂", ["face", "with", "tears", "of", "joy"]),
        EmojiItem("🙂", ["slightly", "smiling", "face"]),
        EmojiItem("🙃", ["upside", "down", "face"]),
        EmojiItem("🫠", ["melting", "face"]),
        EmojiItem("😉", ["winking", "face"]),
        EmojiItem("😊", ["smiling", "face", "with", "smiling", "eyes"]),
        EmojiItem("😇", ["smiling", "face", "with", "halo"]),
        EmojiItem("🥰", ["smiling", "face", "with", "hearts"]),
        EmojiItem("😍", ["smiling", "face", "with", "heart", "eyes"]),
        EmojiItem("🤩", ["star", "struck"]),
        EmojiItem("😘", ["face", "blowing", "a", "kiss"]),
        EmojiItem("😗", ["kissing", "face"]),
        EmojiItem("☺️", ["smiling", "face"]),
        EmojiItem("😚", ["kissing", "face", "with", "closed", "eyes"]),
        EmojiItem("😙", ["kissing", "face", "with", "smiling", "eyes"]),
        EmojiItem("🥲", ["smiling", "face", "with", "tear"]),
        EmojiItem("😋", ["face", "savoring", "food"]),
        EmojiItem("😛", ["face", "with", "tongue"]),
        EmojiItem("😜", ["winking", "face", "with", "tongue"]),
        EmojiItem("🤪", ["zany", "face"]),
        EmojiItem("😝", ["squinting", "face", "with", "tongue"]),
        EmojiItem("🤑", ["money", "mouth", "face"]),
        EmojiItem("🤗", ["smiling", "face", "with", "open", "hands"]),
        EmojiItem("🤭", ["face", "with", "hand", "over", "mouth"]),
        EmojiItem("🫢", ["face", "with", "open", "eyes", "and", "hand", "over", "mouth"]),
        EmojiItem("🫣", ["face", "with", "peeking", "eye"]),
        EmojiItem("🤫", ["shushing", "face"]),
        EmojiItem("🤔", ["thinking", "face"]),
        EmojiItem("🫡", ["saluting", "face"]),
        EmojiItem("🤐", ["zipper", "mouth", "face"]),
        EmojiItem("🤨", ["face", "with", "raised", "eyebrow"]),
        EmojiItem("😐", ["neutral", "face"]),
        EmojiItem("😑", ["expressionless", "face"]),
        EmojiItem("😶", ["face", "without", "mouth"]),
        EmojiItem("🫥", ["dotted", "line", "face"]),
        EmojiItem("😶‍🌫️", ["face", "in", "clouds"]),
        EmojiItem("😏", ["smirking", "face"]),
        EmojiItem("😒", ["unamused", "face"]),
        EmojiItem("🙄", ["face", "with", "rolling", "eyes"]),
        EmojiItem("😬", ["grimacing", "face"]),
        EmojiItem("😮‍💨", ["face", "exhaling"]),
        EmojiItem("🤥", ["lying", "face"]),
        EmojiItem("🫨", ["shaking", "face"]),
        EmojiItem("🙂‍↔️", ["head", "shaking", "horizontally"]),
        EmojiItem("🙂‍↕️", ["head", "shaking", "vertically"]),
        EmojiItem("😌", ["relieved", "face"]),
        EmojiItem("😔", ["pensive", "face"]),
        EmojiItem("😪", ["sleepy", "face"]),
        EmojiItem("🤤", ["drooling", "face"]),
        EmojiItem("😴", ["sleeping", "face"]),
        EmojiItem("😷", ["face", "with", "medical", "mask"]),
        EmojiItem("🤒", ["face", "with", "thermometer"]),
        EmojiItem("🤕", ["face", "with", "head", "bandage"]),
        EmojiItem("🤢", ["nauseated", "face"]),
        EmojiItem("🤮", ["face", "vomiting"]),
        EmojiItem("🤧", ["sneezing", "face"]),
        EmojiItem("🥵", ["hot", "face"]),
        EmojiItem("🥶", ["cold", "face"]),
        EmojiItem("🥴", ["woozy", "face"]),
        EmojiItem("😵", ["face", "with", "crossed", "out", "eyes"]),
        EmojiItem("😵‍💫", ["face", "with", "spiral", "eyes"]),
        EmojiItem("🤯", ["exploding", "head"]),
        EmojiItem("🤠", ["cowboy", "hat", "face"]),
        EmojiItem("🥳", ["partying", "face"]),
        EmojiItem("🥸", ["disguised", "face"]),
        EmojiItem("😎", ["smiling", "face", "with", "sunglasses"]),
        EmojiItem("🤓", ["nerd", "face"]),
        EmojiItem("🧐", ["face", "with", "monocle"]),
        EmojiItem("😕", ["confused", "face"]),
        EmojiItem("🫤", ["face", "with", "diagonal", "mouth"]),
        EmojiItem("😟", ["worried", "face"]),
        EmojiItem("🙁", ["slightly", "frowning", "face"]),
        EmojiItem("☹️", ["frowning", "face"]),
        EmojiItem("😮", ["face", "with", "open", "mouth"]),
        EmojiItem("😯", ["hushed", "face"]),
        EmojiItem("😲", ["astonished", "face"]),
        EmojiItem("😳", ["flushed", "face"]),
        EmojiItem("🥺", ["pleading", "face"]),
        EmojiItem("🥹", ["face", "holding", "back", "tears"]),
        EmojiItem("😦", ["frowning", "face", "with", "open", "mouth"]),
        EmojiItem("😧", ["anguished", "face"]),
        EmojiItem("😨", ["fearful", "face"]),
        EmojiItem("😰", ["anxious", "face", "with", "sweat"]),
        EmojiItem("😥", ["sad", "but", "relieved", "face"]),
        EmojiItem("😢", ["crying", "face"]),
        EmojiItem("😭", ["loudly", "crying", "face"]),
        EmojiItem("😱", ["face", "screaming", "in", "fear"]),
        EmojiItem("😖", ["confounded", "face"]),
        EmojiItem("😣", ["persevering", "face"]),
        EmojiItem("😞", ["disappointed", "face"]),
        EmojiItem("😓", ["downcast", "face", "with", "sweat"]),
        EmojiItem("😩", ["weary", "face"]),
        EmojiItem("😫", ["tired", "face"]),
        EmojiItem("🥱", ["yawning", "face"]),
        EmojiItem("😤", ["face", "with", "steam", "from", "nose"]),
        EmojiItem("😡", ["enraged", "face"]),
        EmojiItem("😠", ["angry", "face"]),
        EmojiItem("🤬", ["face", "with", "symbols", "on", "mouth"]),
        EmojiItem("😈", ["smiling", "face", "with", "horns"]),
        EmojiItem("👿", ["angry", "face", "with", "horns"]),
        EmojiItem("💀", ["skull"]),
        EmojiItem("☠️", ["skull", "and", "crossbones"]),
        EmojiItem("💩", ["pile", "of", "poo"]),
        EmojiItem("🤡", ["clown", "face"]),
        EmojiItem("👹", ["ogre"]),
        EmojiItem("👺", ["goblin"]),
        EmojiItem("👻", ["ghost"]),
        EmojiItem("👽", ["alien"]),
        EmojiItem("👾", ["alien", "monster"]),
        EmojiItem("🤖", ["robot"]),
        EmojiItem("😺", ["grinning", "cat"]),
        EmojiItem("😸", ["grinning", "cat", "with", "smiling", "eyes"]),
        EmojiItem("😹", ["cat", "with", "tears", "of", "joy"]),
        EmojiItem("😻", ["smiling", "cat", "with", "heart", "eyes"]),
        EmojiItem("😼", ["cat", "with", "wry", "smile"]),
        EmojiItem("😽", ["kissing", "cat"]),
        EmojiItem("🙀", ["weary", "cat"]),
        EmojiItem("😿", ["crying", "cat"]),
        EmojiItem("😾", ["pouting", "cat"]),
        EmojiItem("🙈", ["see", "no", "evil", "monkey"]),
        EmojiItem("🙉", ["hear", "no", "evil", "monkey"]),
        EmojiItem("🙊", ["speak", "no", "evil", "monkey"]),
        EmojiItem("💌", ["love", "letter"]),
        EmojiItem("💘", ["heart", "with", "arrow"]),
        EmojiItem("💝", ["heart", "with", "ribbon"]),
        EmojiItem("💖", ["sparkling", "heart"]),
        EmojiItem("💗", ["growing", "heart"]),
        EmojiItem("💓", ["beating", "heart"]),
        EmojiItem("💞", ["revolving", "hearts"]),
        EmojiItem("💕", ["two", "hearts"]),
        EmojiItem("💟", ["heart", "decoration"]),
        EmojiItem("❣️", ["heart", "exclamation"]),
        EmojiItem("💔", ["broken", "heart"]),
        EmojiItem("❤️‍🔥", ["heart", "on", "fire"]),
        EmojiItem("❤️‍🩹", ["mending", "heart"]),
        EmojiItem("❤️", ["red", "heart"]),
        EmojiItem("🩷", ["pink", "heart"]),
        EmojiItem("🧡", ["orange", "heart"]),
        EmojiItem("💛", ["yellow", "heart"]),
        EmojiItem("💚", ["green", "heart"]),
        EmojiItem("💙", ["blue", "heart"]),
        EmojiItem("🩵", ["light", "blue", "heart"]),
        EmojiItem("💜", ["purple", "heart"]),
        EmojiItem("🤎", ["brown", "heart"]),
        EmojiItem("🖤", ["black", "heart"]),
        EmojiItem("🩶", ["grey", "heart"]),
        EmojiItem("🤍", ["white", "heart"]),
        EmojiItem("💋", ["kiss", "mark"]),
        EmojiItem("💯", ["hundred", "points"]),
        EmojiItem("💢", ["anger", "symbol"]),
        EmojiItem("💥", ["collision"]),
        EmojiItem("💫", ["dizzy"]),
        EmojiItem("💦", ["sweat", "droplets"]),
        EmojiItem("💨", ["dashing", "away"]),
        EmojiItem("🕳️", ["hole"]),
        EmojiItem("💬", ["speech", "balloon"]),
        EmojiItem("👁️‍🗨️", ["eye", "in", "speech", "bubble"]),
        EmojiItem("🗨️", ["left", "speech", "bubble"]),
        EmojiItem("🗯️", ["right", "anger", "bubble"]),
        EmojiItem("💭", ["thought", "balloon"]),
        EmojiItem("💤", ["zzz"]),
        EmojiItem("👋", ["waving", "hand"]),
        EmojiItem("🤚", ["raised", "back", "of", "hand"]),
        EmojiItem("🖐️", ["hand", "with", "fingers", "splayed"]),
        EmojiItem("✋", ["raised", "hand"]),
        EmojiItem("🖖", ["vulcan", "salute"]),
        EmojiItem("🫱", ["rightwards", "hand"]),
        EmojiItem("🫲", ["leftwards", "hand"]),
        EmojiItem("🫳", ["palm", "down", "hand"]),
        EmojiItem("🫴", ["palm", "up", "hand"]),
        EmojiItem("🫷", ["leftwards", "pushing", "hand"]),
        EmojiItem("🫸", ["rightwards", "pushing", "hand"]),
        EmojiItem("👌", ["ok", "hand"]),
        EmojiItem("🤌", ["pinched", "fingers"]),
        EmojiItem("🤏", ["pinching", "hand"]),
        EmojiItem("✌️", ["victory", "hand"]),
        EmojiItem("🤞", ["crossed", "fingers"]),
        EmojiItem("🫰", ["hand", "with", "index", "finger", "and", "thumb", "crossed"]),
        EmojiItem("🤟", ["love", "you", "gesture"]),
        EmojiItem("🤘", ["sign", "of", "the", "horns"]),
        EmojiItem("🤙", ["call", "me", "hand"]),
        EmojiItem("👈", ["backhand", "index", "pointing", "left"]),
        EmojiItem("👉", ["backhand", "index", "pointing", "right"]),
        EmojiItem("👆", ["backhand", "index", "pointing", "up"]),
        EmojiItem("🖕", ["middle", "finger"]),
        EmojiItem("👇", ["backhand", "index", "pointing", "down"]),
        EmojiItem("☝️", ["index", "pointing", "up"]),
        EmojiItem("🫵", ["index", "pointing", "at", "the", "viewer"]),
        EmojiItem("👍", ["thumbs", "up"]),
        EmojiItem("👎", ["thumbs", "down"]),
        EmojiItem("✊", ["raised", "fist"]),
        EmojiItem("👊", ["oncoming", "fist"]),
        EmojiItem("🤛", ["left", "facing", "fist"]),
        EmojiItem("🤜", ["right", "facing", "fist"]),
        EmojiItem("👏", ["clapping", "hands"]),
        EmojiItem("🙌", ["raising", "hands"]),
        EmojiItem("🫶", ["heart", "hands"]),
        EmojiItem("👐", ["open", "hands"]),
        EmojiItem("🤲", ["palms", "up", "together"]),
        EmojiItem("🤝", ["handshake"]),
        EmojiItem("🙏", ["folded", "hands"]),
        EmojiItem("✍️", ["writing", "hand"]),
        EmojiItem("💅", ["nail", "polish"]),
        EmojiItem("🤳", ["selfie"]),
        EmojiItem("💪", ["flexed", "biceps"]),
        EmojiItem("🦾", ["mechanical", "arm"]),
        EmojiItem("🦿", ["mechanical", "leg"]),
        EmojiItem("🦵", ["leg"]),
        EmojiItem("🦶", ["foot"]),
        EmojiItem("👂", ["ear"]),
        EmojiItem("🦻", ["ear", "with", "hearing", "aid"]),
        EmojiItem("👃", ["nose"]),
        EmojiItem("🧠", ["brain"]),
        EmojiItem("🫀", ["anatomical", "heart"]),
        EmojiItem("🫁", ["lungs"]),
        EmojiItem("🦷", ["tooth"]),
        EmojiItem("🦴", ["bone"]),
        EmojiItem("👀", ["eyes"]),
        EmojiItem("👁️", ["eye"]),
        EmojiItem("👅", ["tongue"]),
        EmojiItem("👄", ["mouth"]),
        EmojiItem("🫦", ["biting", "lip"]),
        EmojiItem("👶", ["baby"]),
        EmojiItem("🧒", ["child"]),
        EmojiItem("👦", ["boy"]),
        EmojiItem("👧", ["girl"]),
        EmojiItem("🧑", ["person"]),
        EmojiItem("👱", ["person", "blond", "hair"]),
        EmojiItem("👨", ["man"]),
        EmojiItem("🧔", ["person", "beard"]),
        EmojiItem("🧔‍♂️", ["man", "beard"]),
        EmojiItem("🧔‍♀️", ["woman", "beard"]),
        EmojiItem("👨‍🦰", ["man", "red", "hair"]),
        EmojiItem("👨‍🦱", ["man", "curly", "hair"]),
        EmojiItem("👨‍🦳", ["man", "white", "hair"]),
        EmojiItem("👨‍🦲", ["man", "bald"]),
        EmojiItem("👩", ["woman"]),
        EmojiItem("👩‍🦰", ["woman", "red", "hair"]),
        EmojiItem("🧑‍🦰", ["person", "red", "hair"]),
        EmojiItem("👩‍🦱", ["woman", "curly", "hair"]),
        EmojiItem("🧑‍🦱", ["person", "curly", "hair"]),
        EmojiItem("👩‍🦳", ["woman", "white", "hair"]),
        EmojiItem("🧑‍🦳", ["person", "white", "hair"]),
        EmojiItem("👩‍🦲", ["woman", "bald"]),
        EmojiItem("🧑‍🦲", ["person", "bald"]),
        EmojiItem("👱‍♀️", ["woman", "blond", "hair"]),
        EmojiItem("👱‍♂️", ["man", "blond", "hair"]),
        EmojiItem("🧓", ["older", "person"]),
        EmojiItem("👴", ["old", "man"]),
        EmojiItem("👵", ["old", "woman"]),
        EmojiItem("🙍", ["person", "frowning"]),
        EmojiItem("🙍‍♂️", ["man", "frowning"]),
        EmojiItem("🙍‍♀️", ["woman", "frowning"]),
        EmojiItem("🙎", ["person", "pouting"]),
        EmojiItem("🙎‍♂️", ["man", "pouting"]),
        EmojiItem("🙎‍♀️", ["woman", "pouting"]),
        EmojiItem("🙅", ["person", "gesturing", "no"]),
        EmojiItem("🙅‍♂️", ["man", "gesturing", "no"]),
        EmojiItem("🙅‍♀️", ["woman", "gesturing", "no"]),
        EmojiItem("🙆", ["person", "gesturing", "ok"]),
        EmojiItem("🙆‍♂️", ["man", "gesturing", "ok"]),
        EmojiItem("🙆‍♀️", ["woman", "gesturing", "ok"]),
        EmojiItem("💁", ["person", "tipping", "hand"]),
        EmojiItem("💁‍♂️", ["man", "tipping", "hand"]),
        EmojiItem("💁‍♀️", ["woman", "tipping", "hand"]),
        EmojiItem("🙋", ["person", "raising", "hand"]),
        EmojiItem("🙋‍♂️", ["man", "raising", "hand"]),
        EmojiItem("🙋‍♀️", ["woman", "raising", "hand"]),
        EmojiItem("🧏", ["deaf", "person"]),
        EmojiItem("🧏‍♂️", ["deaf", "man"]),
        EmojiItem("🧏‍♀️", ["deaf", "woman"]),
        EmojiItem("🙇", ["person", "bowing"]),
        EmojiItem("🙇‍♂️", ["man", "bowing"]),
        EmojiItem("🙇‍♀️", ["woman", "bowing"]),
        EmojiItem("🤦", ["person", "facepalming"]),
        EmojiItem("🤦‍♂️", ["man", "facepalming"]),
        EmojiItem("🤦‍♀️", ["woman", "facepalming"]),
        EmojiItem("🤷", ["person", "shrugging"]),
        EmojiItem("🤷‍♂️", ["man", "shrugging"]),
        EmojiItem("🤷‍♀️", ["woman", "shrugging"]),
        EmojiItem("🧑‍⚕️", ["health", "worker"]),
        EmojiItem("👨‍⚕️", ["man", "health", "worker"]),
        EmojiItem("👩‍⚕️", ["woman", "health", "worker"]),
        EmojiItem("🧑‍🎓", ["student"]),
        EmojiItem("👨‍🎓", ["man", "student"]),
        EmojiItem("👩‍🎓", ["woman", "student"]),
        EmojiItem("🧑‍🏫", ["teacher"]),
        EmojiItem("👨‍🏫", ["man", "teacher"]),
        EmojiItem("👩‍🏫", ["woman", "teacher"]),
        EmojiItem("🧑‍⚖️", ["judge"]),
        EmojiItem("👨‍⚖️", ["man", "judge"]),
        EmojiItem("👩‍⚖️", ["woman", "judge"]),
        EmojiItem("🧑‍🌾", ["farmer"]),
        EmojiItem("👨‍🌾", ["man", "farmer"]),
        EmojiItem("👩‍🌾", ["woman", "farmer"]),
        EmojiItem("🧑‍🍳", ["cook"]),
        EmojiItem("👨‍🍳", ["man", "cook"]),
        EmojiItem("👩‍🍳", ["woman", "cook"]),
        EmojiItem("🧑‍🔧", ["mechanic"]),
        EmojiItem("👨‍🔧", ["man", "mechanic"]),
        EmojiItem("👩‍🔧", ["woman", "mechanic"]),
        EmojiItem("🧑‍🏭", ["factory", "worker"]),
        EmojiItem("👨‍🏭", ["man", "factory", "worker"]),
        EmojiItem("👩‍🏭", ["woman", "factory", "worker"]),
        EmojiItem("🧑‍💼", ["office", "worker"]),
        EmojiItem("👨‍💼", ["man", "office", "worker"]),
        EmojiItem("👩‍💼", ["woman", "office", "worker"]),
        EmojiItem("🧑‍🔬", ["scientist"]),
        EmojiItem("👨‍🔬", ["man", "scientist"]),
        EmojiItem("👩‍🔬", ["woman", "scientist"]),
        EmojiItem("🧑‍💻", ["technologist"]),
        EmojiItem("👨‍💻", ["man", "technologist"]),
        EmojiItem("👩‍💻", ["woman", "technologist"]),
        EmojiItem("🧑‍🎤", ["singer"]),
        EmojiItem("👨‍🎤", ["man", "singer"]),
        EmojiItem("👩‍🎤", ["woman", "singer"]),
        EmojiItem("🧑‍🎨", ["artist"]),
        EmojiItem("👨‍🎨", ["man", "artist"]),
        EmojiItem("👩‍🎨", ["woman", "artist"]),
        EmojiItem("🧑‍✈️", ["pilot"]),
        EmojiItem("👨‍✈️", ["man", "pilot"]),
        EmojiItem("👩‍✈️", ["woman", "pilot"]),
        EmojiItem("🧑‍🚀", ["astronaut"]),
        EmojiItem("👨‍🚀", ["man", "astronaut"]),
        EmojiItem("👩‍🚀", ["woman", "astronaut"]),
        EmojiItem("🧑‍🚒", ["firefighter"]),
        EmojiItem("👨‍🚒", ["man", "firefighter"]),
        EmojiItem("👩‍🚒", ["woman", "firefighter"]),
        EmojiItem("👮", ["police", "officer"]),
        EmojiItem("👮‍♂️", ["man", "police", "officer"]),
        EmojiItem("👮‍♀️", ["woman", "police", "officer"]),
        EmojiItem("🕵️", ["detective"]),
        EmojiItem("🕵️‍♂️", ["man", "detective"]),
        EmojiItem("🕵️‍♀️", ["woman", "detective"]),
        EmojiItem("💂", ["guard"]),
        EmojiItem("💂‍♂️", ["man", "guard"]),
        EmojiItem("💂‍♀️", ["woman", "guard"]),
        EmojiItem("🥷", ["ninja"]),
        EmojiItem("👷", ["construction", "worker"]),
        EmojiItem("👷‍♂️", ["man", "construction", "worker"]),
        EmojiItem("👷‍♀️", ["woman", "construction", "worker"]),
        EmojiItem("🫅", ["person", "with", "crown"]),
        EmojiItem("🤴", ["prince"]),
        EmojiItem("👸", ["princess"]),
        EmojiItem("👳", ["person", "wearing", "turban"]),
        EmojiItem("👳‍♂️", ["man", "wearing", "turban"]),
        EmojiItem("👳‍♀️", ["woman", "wearing", "turban"]),
        EmojiItem("👲", ["person", "with", "skullcap"]),
        EmojiItem("🧕", ["woman", "with", "headscarf"]),
        EmojiItem("🤵", ["person", "in", "tuxedo"]),
        EmojiItem("🤵‍♂️", ["man", "in", "tuxedo"]),
        EmojiItem("🤵‍♀️", ["woman", "in", "tuxedo"]),
        EmojiItem("👰", ["person", "with", "veil"]),
        EmojiItem("👰‍♂️", ["man", "with", "veil"]),
        EmojiItem("👰‍♀️", ["woman", "with", "veil"]),
        EmojiItem("🤰", ["pregnant", "woman"]),
        EmojiItem("🫃", ["pregnant", "man"]),
        EmojiItem("🫄", ["pregnant", "person"]),
        EmojiItem("🤱", ["breast", "feeding"]),
        EmojiItem("👩‍🍼", ["woman", "feeding", "baby"]),
        EmojiItem("👨‍🍼", ["man", "feeding", "baby"]),
        EmojiItem("🧑‍🍼", ["person", "feeding", "baby"]),
        EmojiItem("👼", ["baby", "angel"]),
        EmojiItem("🎅", ["santa", "claus"]),
        EmojiItem("🤶", ["mrs.", "claus"]),
        EmojiItem("🧑‍🎄", ["mx", "claus"]),
        EmojiItem("🦸", ["superhero"]),
        EmojiItem("🦸‍♂️", ["man", "superhero"]),
        EmojiItem("🦸‍♀️", ["woman", "superhero"]),
        EmojiItem("🦹", ["supervillain"]),
        EmojiItem("🦹‍♂️", ["man", "supervillain"]),
        EmojiItem("🦹‍♀️", ["woman", "supervillain"]),
        EmojiItem("🧙", ["mage"]),
        EmojiItem("🧙‍♂️", ["man", "mage"]),
        EmojiItem("🧙‍♀️", ["woman", "mage"]),
        EmojiItem("🧚", ["fairy"]),
        EmojiItem("🧚‍♂️", ["man", "fairy"]),
        EmojiItem("🧚‍♀️", ["woman", "fairy"]),
        EmojiItem("🧛", ["vampire"]),
        EmojiItem("🧛‍♂️", ["man", "vampire"]),
        EmojiItem("🧛‍♀️", ["woman", "vampire"]),
        EmojiItem("🧜", ["merperson"]),
        EmojiItem("🧜‍♂️", ["merman"]),
        EmojiItem("🧜‍♀️", ["mermaid"]),
        EmojiItem("🧝", ["elf"]),
        EmojiItem("🧝‍♂️", ["man", "elf"]),
        EmojiItem("🧝‍♀️", ["woman", "elf"]),
        EmojiItem("🧞", ["genie"]),
        EmojiItem("🧞‍♂️", ["man", "genie"]),
        EmojiItem("🧞‍♀️", ["woman", "genie"]),
        EmojiItem("🧟", ["zombie"]),
        EmojiItem("🧟‍♂️", ["man", "zombie"]),
        EmojiItem("🧟‍♀️", ["woman", "zombie"]),
        EmojiItem("🧌", ["troll"]),
        EmojiItem("💆", ["person", "getting", "massage"]),
        EmojiItem("💆‍♂️", ["man", "getting", "massage"]),
        EmojiItem("💆‍♀️", ["woman", "getting", "massage"]),
        EmojiItem("💇", ["person", "getting", "haircut"]),
        EmojiItem("💇‍♂️", ["man", "getting", "haircut"]),
        EmojiItem("💇‍♀️", ["woman", "getting", "haircut"]),
        EmojiItem("🚶", ["person", "walking"]),
        EmojiItem("🚶‍♂️", ["man", "walking"]),
        EmojiItem("🚶‍♀️", ["woman", "walking"]),
        EmojiItem("🚶‍➡️", ["person", "walking", "facing", "right"]),
        EmojiItem("🚶‍♀️‍➡️", ["woman", "walking", "facing", "right"]),
        EmojiItem("🚶‍♂️‍➡️", ["man", "walking", "facing", "right"]),
        EmojiItem("🧍", ["person", "standing"]),
        EmojiItem("🧍‍♂️", ["man", "standing"]),
        EmojiItem("🧍‍♀️", ["woman", "standing"]),
        EmojiItem("🧎", ["person", "kneeling"]),
        EmojiItem("🧎‍♂️", ["man", "kneeling"]),
        EmojiItem("🧎‍♀️", ["woman", "kneeling"]),
        EmojiItem("🧎‍➡️", ["person", "kneeling", "facing", "right"]),
        EmojiItem("🧎‍♀️‍➡️", ["woman", "kneeling", "facing", "right"]),
        EmojiItem("🧎‍♂️‍➡️", ["man", "kneeling", "facing", "right"]),
        EmojiItem("🧑‍🦯", ["person", "with", "white", "cane"]),
        EmojiItem("🧑‍🦯‍➡️", ["person", "with", "white", "cane", "facing", "right"]),
        EmojiItem("👨‍🦯", ["man", "with", "white", "cane"]),
        EmojiItem("👨‍🦯‍➡️", ["man", "with", "white", "cane", "facing", "right"]),
        EmojiItem("👩‍🦯", ["woman", "with", "white", "cane"]),
        EmojiItem("👩‍🦯‍➡️", ["woman", "with", "white", "cane", "facing", "right"]),
        EmojiItem("🧑‍🦼", ["person", "in", "motorized", "wheelchair"]),
        EmojiItem("🧑‍🦼‍➡️", ["person", "in", "motorized", "wheelchair", "facing", "right"]),
        EmojiItem("👨‍🦼", ["man", "in", "motorized", "wheelchair"]),
        EmojiItem("👨‍🦼‍➡️", ["man", "in", "motorized", "wheelchair", "facing", "right"]),
        EmojiItem("👩‍🦼", ["woman", "in", "motorized", "wheelchair"]),
        EmojiItem("👩‍🦼‍➡️", ["woman", "in", "motorized", "wheelchair", "facing", "right"]),
        EmojiItem("🧑‍🦽", ["person", "in", "manual", "wheelchair"]),
        EmojiItem("🧑‍🦽‍➡️", ["person", "in", "manual", "wheelchair", "facing", "right"]),
        EmojiItem("👨‍🦽", ["man", "in", "manual", "wheelchair"]),
        EmojiItem("👨‍🦽‍➡️", ["man", "in", "manual", "wheelchair", "facing", "right"]),
        EmojiItem("👩‍🦽", ["woman", "in", "manual", "wheelchair"]),
        EmojiItem("👩‍🦽‍➡️", ["woman", "in", "manual", "wheelchair", "facing", "right"]),
        EmojiItem("🏃", ["person", "running"]),
        EmojiItem("🏃‍♂️", ["man", "running"]),
        EmojiItem("🏃‍♀️", ["woman", "running"]),
        EmojiItem("🏃‍➡️", ["person", "running", "facing", "right"]),
        EmojiItem("🏃‍♀️‍➡️", ["woman", "running", "facing", "right"]),
        EmojiItem("🏃‍♂️‍➡️", ["man", "running", "facing", "right"]),
        EmojiItem("💃", ["woman", "dancing"]),
        EmojiItem("🕺", ["man", "dancing"]),
        EmojiItem("🕴️", ["person", "in", "suit", "levitating"]),
        EmojiItem("👯", ["people", "with", "bunny", "ears"]),
        EmojiItem("👯‍♂️", ["men", "with", "bunny", "ears"]),
        EmojiItem("👯‍♀️", ["women", "with", "bunny", "ears"]),
        EmojiItem("🧖", ["person", "in", "steamy", "room"]),
        EmojiItem("🧖‍♂️", ["man", "in", "steamy", "room"]),
        EmojiItem("🧖‍♀️", ["woman", "in", "steamy", "room"]),
        EmojiItem("🧗", ["person", "climbing"]),
        EmojiItem("🧗‍♂️", ["man", "climbing"]),
        EmojiItem("🧗‍♀️", ["woman", "climbing"]),
        EmojiItem("🤺", ["person", "fencing"]),
        EmojiItem("🏇", ["horse", "racing"]),
        EmojiItem("⛷️", ["skier"]),
        EmojiItem("🏂", ["snowboarder"]),
        EmojiItem("🏌️", ["person", "golfing"]),
        EmojiItem("🏌️‍♂️", ["man", "golfing"]),
        EmojiItem("🏌️‍♀️", ["woman", "golfing"]),
        EmojiItem("🏄", ["person", "surfing"]),
        EmojiItem("🏄‍♂️", ["man", "surfing"]),
        EmojiItem("🏄‍♀️", ["woman", "surfing"]),
        EmojiItem("🚣", ["person", "rowing", "boat"]),
        EmojiItem("🚣‍♂️", ["man", "rowing", "boat"]),
        EmojiItem("🚣‍♀️", ["woman", "rowing", "boat"]),
        EmojiItem("🏊", ["person", "swimming"]),
        EmojiItem("🏊‍♂️", ["man", "swimming"]),
        EmojiItem("🏊‍♀️", ["woman", "swimming"]),
        EmojiItem("⛹️", ["person", "bouncing", "ball"]),
        EmojiItem("⛹️‍♂️", ["man", "bouncing", "ball"]),
        EmojiItem("⛹️‍♀️", ["woman", "bouncing", "ball"]),
        EmojiItem("🏋️", ["person", "lifting", "weights"]),
        EmojiItem("🏋️‍♂️", ["man", "lifting", "weights"]),
        EmojiItem("🏋️‍♀️", ["woman", "lifting", "weights"]),
        EmojiItem("🚴", ["person", "biking"]),
        EmojiItem("🚴‍♂️", ["man", "biking"]),
        EmojiItem("🚴‍♀️", ["woman", "biking"]),
        EmojiItem("🚵", ["person", "mountain", "biking"]),
        EmojiItem("🚵‍♂️", ["man", "mountain", "biking"]),
        EmojiItem("🚵‍♀️", ["woman", "mountain", "biking"]),
        EmojiItem("🤸", ["person", "cartwheeling"]),
        EmojiItem("🤸‍♂️", ["man", "cartwheeling"]),
        EmojiItem("🤸‍♀️", ["woman", "cartwheeling"]),
        EmojiItem("🤼", ["people", "wrestling"]),
        EmojiItem("🤼‍♂️", ["men", "wrestling"]),
        EmojiItem("🤼‍♀️", ["women", "wrestling"]),
        EmojiItem("🤽", ["person", "playing", "water", "polo"]),
        EmojiItem("🤽‍♂️", ["man", "playing", "water", "polo"]),
        EmojiItem("🤽‍♀️", ["woman", "playing", "water", "polo"]),
        EmojiItem("🤾", ["person", "playing", "handball"]),
        EmojiItem("🤾‍♂️", ["man", "playing", "handball"]),
        EmojiItem("🤾‍♀️", ["woman", "playing", "handball"]),
        EmojiItem("🤹", ["person", "juggling"]),
        EmojiItem("🤹‍♂️", ["man", "juggling"]),
        EmojiItem("🤹‍♀️", ["woman", "juggling"]),
        EmojiItem("🧘", ["person", "in", "lotus", "position"]),
        EmojiItem("🧘‍♂️", ["man", "in", "lotus", "position"]),
        EmojiItem("🧘‍♀️", ["woman", "in", "lotus", "position"]),
        EmojiItem("🛀", ["person", "taking", "bath"]),
        EmojiItem("🛌", ["person", "in", "bed"]),
        EmojiItem("🧑‍🤝‍🧑", ["people", "holding", "hands"]),
        EmojiItem("👭", ["women", "holding", "hands"]),
        EmojiItem("👫", ["woman", "and", "man", "holding", "hands"]),
        EmojiItem("👬", ["men", "holding", "hands"]),
        EmojiItem("💏", ["kiss"]),
        EmojiItem("👩‍❤️‍💋‍👨", ["kiss", "woman", "man"]),
        EmojiItem("👨‍❤️‍💋‍👨", ["kiss", "man", "man"]),
        EmojiItem("👩‍❤️‍💋‍👩", ["kiss", "woman", "woman"]),
        EmojiItem("💑", ["couple", "with", "heart"]),
        EmojiItem("👩‍❤️‍👨", ["couple", "with", "heart", "woman", "man"]),
        EmojiItem("👨‍❤️‍👨", ["couple", "with", "heart", "man", "man"]),
        EmojiItem("👩‍❤️‍👩", ["couple", "with", "heart", "woman", "woman"]),
        EmojiItem("👨‍👩‍👦", ["family", "man", "woman", "boy"]),
        EmojiItem("👨‍👩‍👧", ["family", "man", "woman", "girl"]),
        EmojiItem("👨‍👩‍👧‍👦", ["family", "man", "woman", "girl", "boy"]),
        EmojiItem("👨‍👩‍👦‍👦", ["family", "man", "woman", "boy", "boy"]),
        EmojiItem("👨‍👩‍👧‍👧", ["family", "man", "woman", "girl", "girl"]),
        EmojiItem("👨‍👨‍👦", ["family", "man", "man", "boy"]),
        EmojiItem("👨‍👨‍👧", ["family", "man", "man", "girl"]),
        EmojiItem("👨‍👨‍👧‍👦", ["family", "man", "man", "girl", "boy"]),
        EmojiItem("👨‍👨‍👦‍👦", ["family", "man", "man", "boy", "boy"]),
        EmojiItem("👨‍👨‍👧‍👧", ["family", "man", "man", "girl", "girl"]),
        EmojiItem("👩‍👩‍👦", ["family", "woman", "woman", "boy"]),
        EmojiItem("👩‍👩‍👧", ["family", "woman", "woman", "girl"]),
        EmojiItem("👩‍👩‍👧‍👦", ["family", "woman", "woman", "girl", "boy"]),
        EmojiItem("👩‍👩‍👦‍👦", ["family", "woman", "woman", "boy", "boy"]),
        EmojiItem("👩‍👩‍👧‍👧", ["family", "woman", "woman", "girl", "girl"]),
        EmojiItem("👨‍👦", ["family", "man", "boy"]),
        EmojiItem("👨‍👦‍👦", ["family", "man", "boy", "boy"]),
        EmojiItem("👨‍👧", ["family", "man", "girl"]),
        EmojiItem("👨‍👧‍👦", ["family", "man", "girl", "boy"]),
        EmojiItem("👨‍👧‍👧", ["family", "man", "girl", "girl"]),
        EmojiItem("👩‍👦", ["family", "woman", "boy"]),
        EmojiItem("👩‍👦‍👦", ["family", "woman", "boy", "boy"]),
        EmojiItem("👩‍👧", ["family", "woman", "girl"]),
        EmojiItem("👩‍👧‍👦", ["family", "woman", "girl", "boy"]),
        EmojiItem("👩‍👧‍👧", ["family", "woman", "girl", "girl"]),
        EmojiItem("🗣️", ["speaking", "head"]),
        EmojiItem("👤", ["bust", "in", "silhouette"]),
        EmojiItem("👥", ["busts", "in", "silhouette"]),
        EmojiItem("🫂", ["people", "hugging"]),
        EmojiItem("👪", ["family"]),
        EmojiItem("🧑‍🧑‍🧒", ["family", "adult", "adult", "child"]),
        EmojiItem("🧑‍🧑‍🧒‍🧒", ["family", "adult", "adult", "child", "child"]),
        EmojiItem("🧑‍🧒", ["family", "adult", "child"]),
        EmojiItem("🧑‍🧒‍🧒", ["family", "adult", "child", "child"]),
        EmojiItem("👣", ["footprints"]),
    ]

    // MARK: - Animals & Nature (153)
    static let animals: [EmojiItem] = [
        EmojiItem("🐵", ["monkey", "face"]),
        EmojiItem("🐒", ["monkey"]),
        EmojiItem("🦍", ["gorilla"]),
        EmojiItem("🦧", ["orangutan"]),
        EmojiItem("🐶", ["dog", "face"]),
        EmojiItem("🐕", ["dog"]),
        EmojiItem("🦮", ["guide", "dog"]),
        EmojiItem("🐕‍🦺", ["service", "dog"]),
        EmojiItem("🐩", ["poodle"]),
        EmojiItem("🐺", ["wolf"]),
        EmojiItem("🦊", ["fox"]),
        EmojiItem("🦝", ["raccoon"]),
        EmojiItem("🐱", ["cat", "face"]),
        EmojiItem("🐈", ["cat"]),
        EmojiItem("🐈‍⬛", ["black", "cat"]),
        EmojiItem("🦁", ["lion"]),
        EmojiItem("🐯", ["tiger", "face"]),
        EmojiItem("🐅", ["tiger"]),
        EmojiItem("🐆", ["leopard"]),
        EmojiItem("🐴", ["horse", "face"]),
        EmojiItem("🫎", ["moose"]),
        EmojiItem("🫏", ["donkey"]),
        EmojiItem("🐎", ["horse"]),
        EmojiItem("🦄", ["unicorn"]),
        EmojiItem("🦓", ["zebra"]),
        EmojiItem("🦌", ["deer"]),
        EmojiItem("🦬", ["bison"]),
        EmojiItem("🐮", ["cow", "face"]),
        EmojiItem("🐂", ["ox"]),
        EmojiItem("🐃", ["water", "buffalo"]),
        EmojiItem("🐄", ["cow"]),
        EmojiItem("🐷", ["pig", "face"]),
        EmojiItem("🐖", ["pig"]),
        EmojiItem("🐗", ["boar"]),
        EmojiItem("🐽", ["pig", "nose"]),
        EmojiItem("🐏", ["ram"]),
        EmojiItem("🐑", ["ewe"]),
        EmojiItem("🐐", ["goat"]),
        EmojiItem("🐪", ["camel"]),
        EmojiItem("🐫", ["two", "hump", "camel"]),
        EmojiItem("🦙", ["llama"]),
        EmojiItem("🦒", ["giraffe"]),
        EmojiItem("🐘", ["elephant"]),
        EmojiItem("🦣", ["mammoth"]),
        EmojiItem("🦏", ["rhinoceros"]),
        EmojiItem("🦛", ["hippopotamus"]),
        EmojiItem("🐭", ["mouse", "face"]),
        EmojiItem("🐁", ["mouse"]),
        EmojiItem("🐀", ["rat"]),
        EmojiItem("🐹", ["hamster"]),
        EmojiItem("🐰", ["rabbit", "face"]),
        EmojiItem("🐇", ["rabbit"]),
        EmojiItem("🐿️", ["chipmunk"]),
        EmojiItem("🦫", ["beaver"]),
        EmojiItem("🦔", ["hedgehog"]),
        EmojiItem("🦇", ["bat"]),
        EmojiItem("🐻", ["bear"]),
        EmojiItem("🐻‍❄️", ["polar", "bear"]),
        EmojiItem("🐨", ["koala"]),
        EmojiItem("🐼", ["panda"]),
        EmojiItem("🦥", ["sloth"]),
        EmojiItem("🦦", ["otter"]),
        EmojiItem("🦨", ["skunk"]),
        EmojiItem("🦘", ["kangaroo"]),
        EmojiItem("🦡", ["badger"]),
        EmojiItem("🐾", ["paw", "prints"]),
        EmojiItem("🦃", ["turkey"]),
        EmojiItem("🐔", ["chicken"]),
        EmojiItem("🐓", ["rooster"]),
        EmojiItem("🐣", ["hatching", "chick"]),
        EmojiItem("🐤", ["baby", "chick"]),
        EmojiItem("🐥", ["front", "facing", "baby", "chick"]),
        EmojiItem("🐦", ["bird"]),
        EmojiItem("🐧", ["penguin"]),
        EmojiItem("🕊️", ["dove"]),
        EmojiItem("🦅", ["eagle"]),
        EmojiItem("🦆", ["duck"]),
        EmojiItem("🦢", ["swan"]),
        EmojiItem("🦉", ["owl"]),
        EmojiItem("🦤", ["dodo"]),
        EmojiItem("🪶", ["feather"]),
        EmojiItem("🦩", ["flamingo"]),
        EmojiItem("🦚", ["peacock"]),
        EmojiItem("🦜", ["parrot"]),
        EmojiItem("🪽", ["wing"]),
        EmojiItem("🐦‍⬛", ["black", "bird"]),
        EmojiItem("🪿", ["goose"]),
        EmojiItem("🐦‍🔥", ["phoenix"]),
        EmojiItem("🐸", ["frog"]),
        EmojiItem("🐊", ["crocodile"]),
        EmojiItem("🐢", ["turtle"]),
        EmojiItem("🦎", ["lizard"]),
        EmojiItem("🐍", ["snake"]),
        EmojiItem("🐲", ["dragon", "face"]),
        EmojiItem("🐉", ["dragon"]),
        EmojiItem("🦕", ["sauropod"]),
        EmojiItem("🦖", ["t", "rex"]),
        EmojiItem("🐳", ["spouting", "whale"]),
        EmojiItem("🐋", ["whale"]),
        EmojiItem("🐬", ["dolphin"]),
        EmojiItem("🦭", ["seal"]),
        EmojiItem("🐟", ["fish"]),
        EmojiItem("🐠", ["tropical", "fish"]),
        EmojiItem("🐡", ["blowfish"]),
        EmojiItem("🦈", ["shark"]),
        EmojiItem("🐙", ["octopus"]),
        EmojiItem("🐚", ["spiral", "shell"]),
        EmojiItem("🪸", ["coral"]),
        EmojiItem("🪼", ["jellyfish"]),
        EmojiItem("🐌", ["snail"]),
        EmojiItem("🦋", ["butterfly"]),
        EmojiItem("🐛", ["bug"]),
        EmojiItem("🐜", ["ant"]),
        EmojiItem("🐝", ["honeybee"]),
        EmojiItem("🪲", ["beetle"]),
        EmojiItem("🐞", ["lady", "beetle"]),
        EmojiItem("🦗", ["cricket"]),
        EmojiItem("🪳", ["cockroach"]),
        EmojiItem("🕷️", ["spider"]),
        EmojiItem("🕸️", ["spider", "web"]),
        EmojiItem("🦂", ["scorpion"]),
        EmojiItem("🦟", ["mosquito"]),
        EmojiItem("🪰", ["fly"]),
        EmojiItem("🪱", ["worm"]),
        EmojiItem("🦠", ["microbe"]),
        EmojiItem("💐", ["bouquet"]),
        EmojiItem("🌸", ["cherry", "blossom"]),
        EmojiItem("💮", ["white", "flower"]),
        EmojiItem("🪷", ["lotus"]),
        EmojiItem("🏵️", ["rosette"]),
        EmojiItem("🌹", ["rose"]),
        EmojiItem("🥀", ["wilted", "flower"]),
        EmojiItem("🌺", ["hibiscus"]),
        EmojiItem("🌻", ["sunflower"]),
        EmojiItem("🌼", ["blossom"]),
        EmojiItem("🌷", ["tulip"]),
        EmojiItem("🪻", ["hyacinth"]),
        EmojiItem("🌱", ["seedling"]),
        EmojiItem("🪴", ["potted", "plant"]),
        EmojiItem("🌲", ["evergreen", "tree"]),
        EmojiItem("🌳", ["deciduous", "tree"]),
        EmojiItem("🌴", ["palm", "tree"]),
        EmojiItem("🌵", ["cactus"]),
        EmojiItem("🌾", ["sheaf", "of", "rice"]),
        EmojiItem("🌿", ["herb"]),
        EmojiItem("☘️", ["shamrock"]),
        EmojiItem("🍀", ["four", "leaf", "clover"]),
        EmojiItem("🍁", ["maple", "leaf"]),
        EmojiItem("🍂", ["fallen", "leaf"]),
        EmojiItem("🍃", ["leaf", "fluttering", "in", "wind"]),
        EmojiItem("🪹", ["empty", "nest"]),
        EmojiItem("🪺", ["nest", "with", "eggs"]),
        EmojiItem("🍄", ["mushroom"]),
    ]

    // MARK: - Food & Drink (135)
    static let food: [EmojiItem] = [
        EmojiItem("🍇", ["grapes"]),
        EmojiItem("🍈", ["melon"]),
        EmojiItem("🍉", ["watermelon"]),
        EmojiItem("🍊", ["tangerine"]),
        EmojiItem("🍋", ["lemon"]),
        EmojiItem("🍋‍🟩", ["lime"]),
        EmojiItem("🍌", ["banana"]),
        EmojiItem("🍍", ["pineapple"]),
        EmojiItem("🥭", ["mango"]),
        EmojiItem("🍎", ["red", "apple"]),
        EmojiItem("🍏", ["green", "apple"]),
        EmojiItem("🍐", ["pear"]),
        EmojiItem("🍑", ["peach"]),
        EmojiItem("🍒", ["cherries"]),
        EmojiItem("🍓", ["strawberry"]),
        EmojiItem("🫐", ["blueberries"]),
        EmojiItem("🥝", ["kiwi", "fruit"]),
        EmojiItem("🍅", ["tomato"]),
        EmojiItem("🫒", ["olive"]),
        EmojiItem("🥥", ["coconut"]),
        EmojiItem("🥑", ["avocado"]),
        EmojiItem("🍆", ["eggplant"]),
        EmojiItem("🥔", ["potato"]),
        EmojiItem("🥕", ["carrot"]),
        EmojiItem("🌽", ["ear", "of", "corn"]),
        EmojiItem("🌶️", ["hot", "pepper"]),
        EmojiItem("🫑", ["bell", "pepper"]),
        EmojiItem("🥒", ["cucumber"]),
        EmojiItem("🥬", ["leafy", "green"]),
        EmojiItem("🥦", ["broccoli"]),
        EmojiItem("🧄", ["garlic"]),
        EmojiItem("🧅", ["onion"]),
        EmojiItem("🥜", ["peanuts"]),
        EmojiItem("🫘", ["beans"]),
        EmojiItem("🌰", ["chestnut"]),
        EmojiItem("🫚", ["ginger", "root"]),
        EmojiItem("🫛", ["pea", "pod"]),
        EmojiItem("🍄‍🟫", ["brown", "mushroom"]),
        EmojiItem("🍞", ["bread"]),
        EmojiItem("🥐", ["croissant"]),
        EmojiItem("🥖", ["baguette", "bread"]),
        EmojiItem("🫓", ["flatbread"]),
        EmojiItem("🥨", ["pretzel"]),
        EmojiItem("🥯", ["bagel"]),
        EmojiItem("🥞", ["pancakes"]),
        EmojiItem("🧇", ["waffle"]),
        EmojiItem("🧀", ["cheese", "wedge"]),
        EmojiItem("🍖", ["meat", "on", "bone"]),
        EmojiItem("🍗", ["poultry", "leg"]),
        EmojiItem("🥩", ["cut", "of", "meat"]),
        EmojiItem("🥓", ["bacon"]),
        EmojiItem("🍔", ["hamburger"]),
        EmojiItem("🍟", ["french", "fries"]),
        EmojiItem("🍕", ["pizza"]),
        EmojiItem("🌭", ["hot", "dog"]),
        EmojiItem("🥪", ["sandwich"]),
        EmojiItem("🌮", ["taco"]),
        EmojiItem("🌯", ["burrito"]),
        EmojiItem("🫔", ["tamale"]),
        EmojiItem("🥙", ["stuffed", "flatbread"]),
        EmojiItem("🧆", ["falafel"]),
        EmojiItem("🥚", ["egg"]),
        EmojiItem("🍳", ["cooking"]),
        EmojiItem("🥘", ["shallow", "pan", "of", "food"]),
        EmojiItem("🍲", ["pot", "of", "food"]),
        EmojiItem("🫕", ["fondue"]),
        EmojiItem("🥣", ["bowl", "with", "spoon"]),
        EmojiItem("🥗", ["green", "salad"]),
        EmojiItem("🍿", ["popcorn"]),
        EmojiItem("🧈", ["butter"]),
        EmojiItem("🧂", ["salt"]),
        EmojiItem("🥫", ["canned", "food"]),
        EmojiItem("🍱", ["bento", "box"]),
        EmojiItem("🍘", ["rice", "cracker"]),
        EmojiItem("🍙", ["rice", "ball"]),
        EmojiItem("🍚", ["cooked", "rice"]),
        EmojiItem("🍛", ["curry", "rice"]),
        EmojiItem("🍜", ["steaming", "bowl"]),
        EmojiItem("🍝", ["spaghetti"]),
        EmojiItem("🍠", ["roasted", "sweet", "potato"]),
        EmojiItem("🍢", ["oden"]),
        EmojiItem("🍣", ["sushi"]),
        EmojiItem("🍤", ["fried", "shrimp"]),
        EmojiItem("🍥", ["fish", "cake", "with", "swirl"]),
        EmojiItem("🥮", ["moon", "cake"]),
        EmojiItem("🍡", ["dango"]),
        EmojiItem("🥟", ["dumpling"]),
        EmojiItem("🥠", ["fortune", "cookie"]),
        EmojiItem("🥡", ["takeout", "box"]),
        EmojiItem("🦀", ["crab"]),
        EmojiItem("🦞", ["lobster"]),
        EmojiItem("🦐", ["shrimp"]),
        EmojiItem("🦑", ["squid"]),
        EmojiItem("🦪", ["oyster"]),
        EmojiItem("🍦", ["soft", "ice", "cream"]),
        EmojiItem("🍧", ["shaved", "ice"]),
        EmojiItem("🍨", ["ice", "cream"]),
        EmojiItem("🍩", ["doughnut"]),
        EmojiItem("🍪", ["cookie"]),
        EmojiItem("🎂", ["birthday", "cake"]),
        EmojiItem("🍰", ["shortcake"]),
        EmojiItem("🧁", ["cupcake"]),
        EmojiItem("🥧", ["pie"]),
        EmojiItem("🍫", ["chocolate", "bar"]),
        EmojiItem("🍬", ["candy"]),
        EmojiItem("🍭", ["lollipop"]),
        EmojiItem("🍮", ["custard"]),
        EmojiItem("🍯", ["honey", "pot"]),
        EmojiItem("🍼", ["baby", "bottle"]),
        EmojiItem("🥛", ["glass", "of", "milk"]),
        EmojiItem("☕", ["hot", "beverage"]),
        EmojiItem("🫖", ["teapot"]),
        EmojiItem("🍵", ["teacup", "without", "handle"]),
        EmojiItem("🍶", ["sake"]),
        EmojiItem("🍾", ["bottle", "with", "popping", "cork"]),
        EmojiItem("🍷", ["wine", "glass"]),
        EmojiItem("🍸", ["cocktail", "glass"]),
        EmojiItem("🍹", ["tropical", "drink"]),
        EmojiItem("🍺", ["beer", "mug"]),
        EmojiItem("🍻", ["clinking", "beer", "mugs"]),
        EmojiItem("🥂", ["clinking", "glasses"]),
        EmojiItem("🥃", ["tumbler", "glass"]),
        EmojiItem("🫗", ["pouring", "liquid"]),
        EmojiItem("🥤", ["cup", "with", "straw"]),
        EmojiItem("🧋", ["bubble", "tea"]),
        EmojiItem("🧃", ["beverage", "box"]),
        EmojiItem("🧉", ["mate"]),
        EmojiItem("🧊", ["ice"]),
        EmojiItem("🥢", ["chopsticks"]),
        EmojiItem("🍽️", ["fork", "and", "knife", "with", "plate"]),
        EmojiItem("🍴", ["fork", "and", "knife"]),
        EmojiItem("🥄", ["spoon"]),
        EmojiItem("🔪", ["kitchen", "knife"]),
        EmojiItem("🫙", ["jar"]),
        EmojiItem("🏺", ["amphora"]),
    ]

    // MARK: - Travel & Places (218)
    static let travel: [EmojiItem] = [
        EmojiItem("🌍", ["globe", "showing", "europe", "africa"]),
        EmojiItem("🌎", ["globe", "showing", "americas"]),
        EmojiItem("🌏", ["globe", "showing", "asia", "australia"]),
        EmojiItem("🌐", ["globe", "with", "meridians"]),
        EmojiItem("🗺️", ["world", "map"]),
        EmojiItem("🗾", ["map", "of", "japan"]),
        EmojiItem("🧭", ["compass"]),
        EmojiItem("🏔️", ["snow", "capped", "mountain"]),
        EmojiItem("⛰️", ["mountain"]),
        EmojiItem("🌋", ["volcano"]),
        EmojiItem("🗻", ["mount", "fuji"]),
        EmojiItem("🏕️", ["camping"]),
        EmojiItem("🏖️", ["beach", "with", "umbrella"]),
        EmojiItem("🏜️", ["desert"]),
        EmojiItem("🏝️", ["desert", "island"]),
        EmojiItem("🏞️", ["national", "park"]),
        EmojiItem("🏟️", ["stadium"]),
        EmojiItem("🏛️", ["classical", "building"]),
        EmojiItem("🏗️", ["building", "construction"]),
        EmojiItem("🧱", ["brick"]),
        EmojiItem("🪨", ["rock"]),
        EmojiItem("🪵", ["wood"]),
        EmojiItem("🛖", ["hut"]),
        EmojiItem("🏘️", ["houses"]),
        EmojiItem("🏚️", ["derelict", "house"]),
        EmojiItem("🏠", ["house"]),
        EmojiItem("🏡", ["house", "with", "garden"]),
        EmojiItem("🏢", ["office", "building"]),
        EmojiItem("🏣", ["japanese", "post", "office"]),
        EmojiItem("🏤", ["post", "office"]),
        EmojiItem("🏥", ["hospital"]),
        EmojiItem("🏦", ["bank"]),
        EmojiItem("🏨", ["hotel"]),
        EmojiItem("🏩", ["love", "hotel"]),
        EmojiItem("🏪", ["convenience", "store"]),
        EmojiItem("🏫", ["school"]),
        EmojiItem("🏬", ["department", "store"]),
        EmojiItem("🏭", ["factory"]),
        EmojiItem("🏯", ["japanese", "castle"]),
        EmojiItem("🏰", ["castle"]),
        EmojiItem("💒", ["wedding"]),
        EmojiItem("🗼", ["tokyo", "tower"]),
        EmojiItem("🗽", ["statue", "of", "liberty"]),
        EmojiItem("⛪", ["church"]),
        EmojiItem("🕌", ["mosque"]),
        EmojiItem("🛕", ["hindu", "temple"]),
        EmojiItem("🕍", ["synagogue"]),
        EmojiItem("⛩️", ["shinto", "shrine"]),
        EmojiItem("🕋", ["kaaba"]),
        EmojiItem("⛲", ["fountain"]),
        EmojiItem("⛺", ["tent"]),
        EmojiItem("🌁", ["foggy"]),
        EmojiItem("🌃", ["night", "with", "stars"]),
        EmojiItem("🏙️", ["cityscape"]),
        EmojiItem("🌄", ["sunrise", "over", "mountains"]),
        EmojiItem("🌅", ["sunrise"]),
        EmojiItem("🌆", ["cityscape", "at", "dusk"]),
        EmojiItem("🌇", ["sunset"]),
        EmojiItem("🌉", ["bridge", "at", "night"]),
        EmojiItem("♨️", ["hot", "springs"]),
        EmojiItem("🎠", ["carousel", "horse"]),
        EmojiItem("🛝", ["playground", "slide"]),
        EmojiItem("🎡", ["ferris", "wheel"]),
        EmojiItem("🎢", ["roller", "coaster"]),
        EmojiItem("💈", ["barber", "pole"]),
        EmojiItem("🎪", ["circus", "tent"]),
        EmojiItem("🚂", ["locomotive"]),
        EmojiItem("🚃", ["railway", "car"]),
        EmojiItem("🚄", ["high", "speed", "train"]),
        EmojiItem("🚅", ["bullet", "train"]),
        EmojiItem("🚆", ["train"]),
        EmojiItem("🚇", ["metro"]),
        EmojiItem("🚈", ["light", "rail"]),
        EmojiItem("🚉", ["station"]),
        EmojiItem("🚊", ["tram"]),
        EmojiItem("🚝", ["monorail"]),
        EmojiItem("🚞", ["mountain", "railway"]),
        EmojiItem("🚋", ["tram", "car"]),
        EmojiItem("🚌", ["bus"]),
        EmojiItem("🚍", ["oncoming", "bus"]),
        EmojiItem("🚎", ["trolleybus"]),
        EmojiItem("🚐", ["minibus"]),
        EmojiItem("🚑", ["ambulance"]),
        EmojiItem("🚒", ["fire", "engine"]),
        EmojiItem("🚓", ["police", "car"]),
        EmojiItem("🚔", ["oncoming", "police", "car"]),
        EmojiItem("🚕", ["taxi"]),
        EmojiItem("🚖", ["oncoming", "taxi"]),
        EmojiItem("🚗", ["automobile"]),
        EmojiItem("🚘", ["oncoming", "automobile"]),
        EmojiItem("🚙", ["sport", "utility", "vehicle"]),
        EmojiItem("🛻", ["pickup", "truck"]),
        EmojiItem("🚚", ["delivery", "truck"]),
        EmojiItem("🚛", ["articulated", "lorry"]),
        EmojiItem("🚜", ["tractor"]),
        EmojiItem("🏎️", ["racing", "car"]),
        EmojiItem("🏍️", ["motorcycle"]),
        EmojiItem("🛵", ["motor", "scooter"]),
        EmojiItem("🦽", ["manual", "wheelchair"]),
        EmojiItem("🦼", ["motorized", "wheelchair"]),
        EmojiItem("🛺", ["auto", "rickshaw"]),
        EmojiItem("🚲", ["bicycle"]),
        EmojiItem("🛴", ["kick", "scooter"]),
        EmojiItem("🛹", ["skateboard"]),
        EmojiItem("🛼", ["roller", "skate"]),
        EmojiItem("🚏", ["bus", "stop"]),
        EmojiItem("🛣️", ["motorway"]),
        EmojiItem("🛤️", ["railway", "track"]),
        EmojiItem("🛢️", ["oil", "drum"]),
        EmojiItem("⛽", ["fuel", "pump"]),
        EmojiItem("🛞", ["wheel"]),
        EmojiItem("🚨", ["police", "car", "light"]),
        EmojiItem("🚥", ["horizontal", "traffic", "light"]),
        EmojiItem("🚦", ["vertical", "traffic", "light"]),
        EmojiItem("🛑", ["stop", "sign"]),
        EmojiItem("🚧", ["construction"]),
        EmojiItem("⚓", ["anchor"]),
        EmojiItem("🛟", ["ring", "buoy"]),
        EmojiItem("⛵", ["sailboat"]),
        EmojiItem("🛶", ["canoe"]),
        EmojiItem("🚤", ["speedboat"]),
        EmojiItem("🛳️", ["passenger", "ship"]),
        EmojiItem("⛴️", ["ferry"]),
        EmojiItem("🛥️", ["motor", "boat"]),
        EmojiItem("🚢", ["ship"]),
        EmojiItem("✈️", ["airplane"]),
        EmojiItem("🛩️", ["small", "airplane"]),
        EmojiItem("🛫", ["airplane", "departure"]),
        EmojiItem("🛬", ["airplane", "arrival"]),
        EmojiItem("🪂", ["parachute"]),
        EmojiItem("💺", ["seat"]),
        EmojiItem("🚁", ["helicopter"]),
        EmojiItem("🚟", ["suspension", "railway"]),
        EmojiItem("🚠", ["mountain", "cableway"]),
        EmojiItem("🚡", ["aerial", "tramway"]),
        EmojiItem("🛰️", ["satellite"]),
        EmojiItem("🚀", ["rocket"]),
        EmojiItem("🛸", ["flying", "saucer"]),
        EmojiItem("🛎️", ["bellhop", "bell"]),
        EmojiItem("🧳", ["luggage"]),
        EmojiItem("⌛", ["hourglass", "done"]),
        EmojiItem("⏳", ["hourglass", "not", "done"]),
        EmojiItem("⌚", ["watch"]),
        EmojiItem("⏰", ["alarm", "clock"]),
        EmojiItem("⏱️", ["stopwatch"]),
        EmojiItem("⏲️", ["timer", "clock"]),
        EmojiItem("🕰️", ["mantelpiece", "clock"]),
        EmojiItem("🕛", ["twelve", "o’clock"]),
        EmojiItem("🕧", ["twelve", "thirty"]),
        EmojiItem("🕐", ["one", "o’clock"]),
        EmojiItem("🕜", ["one", "thirty"]),
        EmojiItem("🕑", ["two", "o’clock"]),
        EmojiItem("🕝", ["two", "thirty"]),
        EmojiItem("🕒", ["three", "o’clock"]),
        EmojiItem("🕞", ["three", "thirty"]),
        EmojiItem("🕓", ["four", "o’clock"]),
        EmojiItem("🕟", ["four", "thirty"]),
        EmojiItem("🕔", ["five", "o’clock"]),
        EmojiItem("🕠", ["five", "thirty"]),
        EmojiItem("🕕", ["six", "o’clock"]),
        EmojiItem("🕡", ["six", "thirty"]),
        EmojiItem("🕖", ["seven", "o’clock"]),
        EmojiItem("🕢", ["seven", "thirty"]),
        EmojiItem("🕗", ["eight", "o’clock"]),
        EmojiItem("🕣", ["eight", "thirty"]),
        EmojiItem("🕘", ["nine", "o’clock"]),
        EmojiItem("🕤", ["nine", "thirty"]),
        EmojiItem("🕙", ["ten", "o’clock"]),
        EmojiItem("🕥", ["ten", "thirty"]),
        EmojiItem("🕚", ["eleven", "o’clock"]),
        EmojiItem("🕦", ["eleven", "thirty"]),
        EmojiItem("🌑", ["new", "moon"]),
        EmojiItem("🌒", ["waxing", "crescent", "moon"]),
        EmojiItem("🌓", ["first", "quarter", "moon"]),
        EmojiItem("🌔", ["waxing", "gibbous", "moon"]),
        EmojiItem("🌕", ["full", "moon"]),
        EmojiItem("🌖", ["waning", "gibbous", "moon"]),
        EmojiItem("🌗", ["last", "quarter", "moon"]),
        EmojiItem("🌘", ["waning", "crescent", "moon"]),
        EmojiItem("🌙", ["crescent", "moon"]),
        EmojiItem("🌚", ["new", "moon", "face"]),
        EmojiItem("🌛", ["first", "quarter", "moon", "face"]),
        EmojiItem("🌜", ["last", "quarter", "moon", "face"]),
        EmojiItem("🌡️", ["thermometer"]),
        EmojiItem("☀️", ["sun"]),
        EmojiItem("🌝", ["full", "moon", "face"]),
        EmojiItem("🌞", ["sun", "with", "face"]),
        EmojiItem("🪐", ["ringed", "planet"]),
        EmojiItem("⭐", ["star"]),
        EmojiItem("🌟", ["glowing", "star"]),
        EmojiItem("🌠", ["shooting", "star"]),
        EmojiItem("🌌", ["milky", "way"]),
        EmojiItem("☁️", ["cloud"]),
        EmojiItem("⛅", ["sun", "behind", "cloud"]),
        EmojiItem("⛈️", ["cloud", "with", "lightning", "and", "rain"]),
        EmojiItem("🌤️", ["sun", "behind", "small", "cloud"]),
        EmojiItem("🌥️", ["sun", "behind", "large", "cloud"]),
        EmojiItem("🌦️", ["sun", "behind", "rain", "cloud"]),
        EmojiItem("🌧️", ["cloud", "with", "rain"]),
        EmojiItem("🌨️", ["cloud", "with", "snow"]),
        EmojiItem("🌩️", ["cloud", "with", "lightning"]),
        EmojiItem("🌪️", ["tornado"]),
        EmojiItem("🌫️", ["fog"]),
        EmojiItem("🌬️", ["wind", "face"]),
        EmojiItem("🌀", ["cyclone"]),
        EmojiItem("🌈", ["rainbow"]),
        EmojiItem("🌂", ["closed", "umbrella"]),
        EmojiItem("☂️", ["umbrella"]),
        EmojiItem("☔", ["umbrella", "with", "rain", "drops"]),
        EmojiItem("⛱️", ["umbrella", "on", "ground"]),
        EmojiItem("⚡", ["high", "voltage"]),
        EmojiItem("❄️", ["snowflake"]),
        EmojiItem("☃️", ["snowman"]),
        EmojiItem("⛄", ["snowman", "without", "snow"]),
        EmojiItem("☄️", ["comet"]),
        EmojiItem("🔥", ["fire"]),
        EmojiItem("💧", ["droplet"]),
        EmojiItem("🌊", ["water", "wave"]),
    ]

    // MARK: - Activities (85)
    static let activities: [EmojiItem] = [
        EmojiItem("🎃", ["jack", "o", "lantern"]),
        EmojiItem("🎄", ["christmas", "tree"]),
        EmojiItem("🎆", ["fireworks"]),
        EmojiItem("🎇", ["sparkler"]),
        EmojiItem("🧨", ["firecracker"]),
        EmojiItem("✨", ["sparkles"]),
        EmojiItem("🎈", ["balloon"]),
        EmojiItem("🎉", ["party", "popper"]),
        EmojiItem("🎊", ["confetti", "ball"]),
        EmojiItem("🎋", ["tanabata", "tree"]),
        EmojiItem("🎍", ["pine", "decoration"]),
        EmojiItem("🎎", ["japanese", "dolls"]),
        EmojiItem("🎏", ["carp", "streamer"]),
        EmojiItem("🎐", ["wind", "chime"]),
        EmojiItem("🎑", ["moon", "viewing", "ceremony"]),
        EmojiItem("🧧", ["red", "envelope"]),
        EmojiItem("🎀", ["ribbon"]),
        EmojiItem("🎁", ["wrapped", "gift"]),
        EmojiItem("🎗️", ["reminder", "ribbon"]),
        EmojiItem("🎟️", ["admission", "tickets"]),
        EmojiItem("🎫", ["ticket"]),
        EmojiItem("🎖️", ["military", "medal"]),
        EmojiItem("🏆", ["trophy"]),
        EmojiItem("🏅", ["sports", "medal"]),
        EmojiItem("🥇", ["1st", "place", "medal"]),
        EmojiItem("🥈", ["2nd", "place", "medal"]),
        EmojiItem("🥉", ["3rd", "place", "medal"]),
        EmojiItem("⚽", ["soccer", "ball"]),
        EmojiItem("⚾", ["baseball"]),
        EmojiItem("🥎", ["softball"]),
        EmojiItem("🏀", ["basketball"]),
        EmojiItem("🏐", ["volleyball"]),
        EmojiItem("🏈", ["american", "football"]),
        EmojiItem("🏉", ["rugby", "football"]),
        EmojiItem("🎾", ["tennis"]),
        EmojiItem("🥏", ["flying", "disc"]),
        EmojiItem("🎳", ["bowling"]),
        EmojiItem("🏏", ["cricket", "game"]),
        EmojiItem("🏑", ["field", "hockey"]),
        EmojiItem("🏒", ["ice", "hockey"]),
        EmojiItem("🥍", ["lacrosse"]),
        EmojiItem("🏓", ["ping", "pong"]),
        EmojiItem("🏸", ["badminton"]),
        EmojiItem("🥊", ["boxing", "glove"]),
        EmojiItem("🥋", ["martial", "arts", "uniform"]),
        EmojiItem("🥅", ["goal", "net"]),
        EmojiItem("⛳", ["flag", "in", "hole"]),
        EmojiItem("⛸️", ["ice", "skate"]),
        EmojiItem("🎣", ["fishing", "pole"]),
        EmojiItem("🤿", ["diving", "mask"]),
        EmojiItem("🎽", ["running", "shirt"]),
        EmojiItem("🎿", ["skis"]),
        EmojiItem("🛷", ["sled"]),
        EmojiItem("🥌", ["curling", "stone"]),
        EmojiItem("🎯", ["bullseye"]),
        EmojiItem("🪀", ["yo", "yo"]),
        EmojiItem("🪁", ["kite"]),
        EmojiItem("🔫", ["water", "pistol"]),
        EmojiItem("🎱", ["pool", "8", "ball"]),
        EmojiItem("🔮", ["crystal", "ball"]),
        EmojiItem("🪄", ["magic", "wand"]),
        EmojiItem("🎮", ["video", "game"]),
        EmojiItem("🕹️", ["joystick"]),
        EmojiItem("🎰", ["slot", "machine"]),
        EmojiItem("🎲", ["game", "die"]),
        EmojiItem("🧩", ["puzzle", "piece"]),
        EmojiItem("🧸", ["teddy", "bear"]),
        EmojiItem("🪅", ["piñata"]),
        EmojiItem("🪩", ["mirror", "ball"]),
        EmojiItem("🪆", ["nesting", "dolls"]),
        EmojiItem("♠️", ["spade", "suit"]),
        EmojiItem("♥️", ["heart", "suit"]),
        EmojiItem("♦️", ["diamond", "suit"]),
        EmojiItem("♣️", ["club", "suit"]),
        EmojiItem("♟️", ["chess", "pawn"]),
        EmojiItem("🃏", ["joker"]),
        EmojiItem("🀄", ["mahjong", "red", "dragon"]),
        EmojiItem("🎴", ["flower", "playing", "cards"]),
        EmojiItem("🎭", ["performing", "arts"]),
        EmojiItem("🖼️", ["framed", "picture"]),
        EmojiItem("🎨", ["artist", "palette"]),
        EmojiItem("🧵", ["thread"]),
        EmojiItem("🪡", ["sewing", "needle"]),
        EmojiItem("🧶", ["yarn"]),
        EmojiItem("🪢", ["knot"]),
    ]

    // MARK: - Objects (262)
    static let objects: [EmojiItem] = [
        EmojiItem("👓", ["glasses"]),
        EmojiItem("🕶️", ["sunglasses"]),
        EmojiItem("🥽", ["goggles"]),
        EmojiItem("🥼", ["lab", "coat"]),
        EmojiItem("🦺", ["safety", "vest"]),
        EmojiItem("👔", ["necktie"]),
        EmojiItem("👕", ["t", "shirt"]),
        EmojiItem("👖", ["jeans"]),
        EmojiItem("🧣", ["scarf"]),
        EmojiItem("🧤", ["gloves"]),
        EmojiItem("🧥", ["coat"]),
        EmojiItem("🧦", ["socks"]),
        EmojiItem("👗", ["dress"]),
        EmojiItem("👘", ["kimono"]),
        EmojiItem("🥻", ["sari"]),
        EmojiItem("🩱", ["one", "piece", "swimsuit"]),
        EmojiItem("🩲", ["briefs"]),
        EmojiItem("🩳", ["shorts"]),
        EmojiItem("👙", ["bikini"]),
        EmojiItem("👚", ["woman’s", "clothes"]),
        EmojiItem("🪭", ["folding", "hand", "fan"]),
        EmojiItem("👛", ["purse"]),
        EmojiItem("👜", ["handbag"]),
        EmojiItem("👝", ["clutch", "bag"]),
        EmojiItem("🛍️", ["shopping", "bags"]),
        EmojiItem("🎒", ["backpack"]),
        EmojiItem("🩴", ["thong", "sandal"]),
        EmojiItem("👞", ["man’s", "shoe"]),
        EmojiItem("👟", ["running", "shoe"]),
        EmojiItem("🥾", ["hiking", "boot"]),
        EmojiItem("🥿", ["flat", "shoe"]),
        EmojiItem("👠", ["high", "heeled", "shoe"]),
        EmojiItem("👡", ["woman’s", "sandal"]),
        EmojiItem("🩰", ["ballet", "shoes"]),
        EmojiItem("👢", ["woman’s", "boot"]),
        EmojiItem("🪮", ["hair", "pick"]),
        EmojiItem("👑", ["crown"]),
        EmojiItem("👒", ["woman’s", "hat"]),
        EmojiItem("🎩", ["top", "hat"]),
        EmojiItem("🎓", ["graduation", "cap"]),
        EmojiItem("🧢", ["billed", "cap"]),
        EmojiItem("🪖", ["military", "helmet"]),
        EmojiItem("⛑️", ["rescue", "worker’s", "helmet"]),
        EmojiItem("📿", ["prayer", "beads"]),
        EmojiItem("💄", ["lipstick"]),
        EmojiItem("💍", ["ring"]),
        EmojiItem("💎", ["gem", "stone"]),
        EmojiItem("🔇", ["muted", "speaker"]),
        EmojiItem("🔈", ["speaker", "low", "volume"]),
        EmojiItem("🔉", ["speaker", "medium", "volume"]),
        EmojiItem("🔊", ["speaker", "high", "volume"]),
        EmojiItem("📢", ["loudspeaker"]),
        EmojiItem("📣", ["megaphone"]),
        EmojiItem("📯", ["postal", "horn"]),
        EmojiItem("🔔", ["bell"]),
        EmojiItem("🔕", ["bell", "with", "slash"]),
        EmojiItem("🎼", ["musical", "score"]),
        EmojiItem("🎵", ["musical", "note"]),
        EmojiItem("🎶", ["musical", "notes"]),
        EmojiItem("🎙️", ["studio", "microphone"]),
        EmojiItem("🎚️", ["level", "slider"]),
        EmojiItem("🎛️", ["control", "knobs"]),
        EmojiItem("🎤", ["microphone"]),
        EmojiItem("🎧", ["headphone"]),
        EmojiItem("📻", ["radio"]),
        EmojiItem("🎷", ["saxophone"]),
        EmojiItem("🪗", ["accordion"]),
        EmojiItem("🎸", ["guitar"]),
        EmojiItem("🎹", ["musical", "keyboard"]),
        EmojiItem("🎺", ["trumpet"]),
        EmojiItem("🎻", ["violin"]),
        EmojiItem("🪕", ["banjo"]),
        EmojiItem("🥁", ["drum"]),
        EmojiItem("🪘", ["long", "drum"]),
        EmojiItem("🪇", ["maracas"]),
        EmojiItem("🪈", ["flute"]),
        EmojiItem("📱", ["mobile", "phone"]),
        EmojiItem("📲", ["mobile", "phone", "with", "arrow"]),
        EmojiItem("☎️", ["telephone"]),
        EmojiItem("📞", ["telephone", "receiver"]),
        EmojiItem("📟", ["pager"]),
        EmojiItem("📠", ["fax", "machine"]),
        EmojiItem("🔋", ["battery"]),
        EmojiItem("🪫", ["low", "battery"]),
        EmojiItem("🔌", ["electric", "plug"]),
        EmojiItem("💻", ["laptop"]),
        EmojiItem("🖥️", ["desktop", "computer"]),
        EmojiItem("🖨️", ["printer"]),
        EmojiItem("⌨️", ["keyboard"]),
        EmojiItem("🖱️", ["computer", "mouse"]),
        EmojiItem("🖲️", ["trackball"]),
        EmojiItem("💽", ["computer", "disk"]),
        EmojiItem("💾", ["floppy", "disk"]),
        EmojiItem("💿", ["optical", "disk"]),
        EmojiItem("📀", ["dvd"]),
        EmojiItem("🧮", ["abacus"]),
        EmojiItem("🎥", ["movie", "camera"]),
        EmojiItem("🎞️", ["film", "frames"]),
        EmojiItem("📽️", ["film", "projector"]),
        EmojiItem("🎬", ["clapper", "board"]),
        EmojiItem("📺", ["television"]),
        EmojiItem("📷", ["camera"]),
        EmojiItem("📸", ["camera", "with", "flash"]),
        EmojiItem("📹", ["video", "camera"]),
        EmojiItem("📼", ["videocassette"]),
        EmojiItem("🔍", ["magnifying", "glass", "tilted", "left"]),
        EmojiItem("🔎", ["magnifying", "glass", "tilted", "right"]),
        EmojiItem("🕯️", ["candle"]),
        EmojiItem("💡", ["light", "bulb"]),
        EmojiItem("🔦", ["flashlight"]),
        EmojiItem("🏮", ["red", "paper", "lantern"]),
        EmojiItem("🪔", ["diya", "lamp"]),
        EmojiItem("📔", ["notebook", "with", "decorative", "cover"]),
        EmojiItem("📕", ["closed", "book"]),
        EmojiItem("📖", ["open", "book"]),
        EmojiItem("📗", ["green", "book"]),
        EmojiItem("📘", ["blue", "book"]),
        EmojiItem("📙", ["orange", "book"]),
        EmojiItem("📚", ["books"]),
        EmojiItem("📓", ["notebook"]),
        EmojiItem("📒", ["ledger"]),
        EmojiItem("📃", ["page", "with", "curl"]),
        EmojiItem("📜", ["scroll"]),
        EmojiItem("📄", ["page", "facing", "up"]),
        EmojiItem("📰", ["newspaper"]),
        EmojiItem("🗞️", ["rolled", "up", "newspaper"]),
        EmojiItem("📑", ["bookmark", "tabs"]),
        EmojiItem("🔖", ["bookmark"]),
        EmojiItem("🏷️", ["label"]),
        EmojiItem("💰", ["money", "bag"]),
        EmojiItem("🪙", ["coin"]),
        EmojiItem("💴", ["yen", "banknote"]),
        EmojiItem("💵", ["dollar", "banknote"]),
        EmojiItem("💶", ["euro", "banknote"]),
        EmojiItem("💷", ["pound", "banknote"]),
        EmojiItem("💸", ["money", "with", "wings"]),
        EmojiItem("💳", ["credit", "card"]),
        EmojiItem("🧾", ["receipt"]),
        EmojiItem("💹", ["chart", "increasing", "with", "yen"]),
        EmojiItem("✉️", ["envelope"]),
        EmojiItem("📧", ["e", "mail"]),
        EmojiItem("📨", ["incoming", "envelope"]),
        EmojiItem("📩", ["envelope", "with", "arrow"]),
        EmojiItem("📤", ["outbox", "tray"]),
        EmojiItem("📥", ["inbox", "tray"]),
        EmojiItem("📦", ["package"]),
        EmojiItem("📫", ["closed", "mailbox", "with", "raised", "flag"]),
        EmojiItem("📪", ["closed", "mailbox", "with", "lowered", "flag"]),
        EmojiItem("📬", ["open", "mailbox", "with", "raised", "flag"]),
        EmojiItem("📭", ["open", "mailbox", "with", "lowered", "flag"]),
        EmojiItem("📮", ["postbox"]),
        EmojiItem("🗳️", ["ballot", "box", "with", "ballot"]),
        EmojiItem("✏️", ["pencil"]),
        EmojiItem("✒️", ["black", "nib"]),
        EmojiItem("🖋️", ["fountain", "pen"]),
        EmojiItem("🖊️", ["pen"]),
        EmojiItem("🖌️", ["paintbrush"]),
        EmojiItem("🖍️", ["crayon"]),
        EmojiItem("📝", ["memo"]),
        EmojiItem("💼", ["briefcase"]),
        EmojiItem("📁", ["file", "folder"]),
        EmojiItem("📂", ["open", "file", "folder"]),
        EmojiItem("🗂️", ["card", "index", "dividers"]),
        EmojiItem("📅", ["calendar"]),
        EmojiItem("📆", ["tear", "off", "calendar"]),
        EmojiItem("🗒️", ["spiral", "notepad"]),
        EmojiItem("🗓️", ["spiral", "calendar"]),
        EmojiItem("📇", ["card", "index"]),
        EmojiItem("📈", ["chart", "increasing"]),
        EmojiItem("📉", ["chart", "decreasing"]),
        EmojiItem("📊", ["bar", "chart"]),
        EmojiItem("📋", ["clipboard"]),
        EmojiItem("📌", ["pushpin"]),
        EmojiItem("📍", ["round", "pushpin"]),
        EmojiItem("📎", ["paperclip"]),
        EmojiItem("🖇️", ["linked", "paperclips"]),
        EmojiItem("📏", ["straight", "ruler"]),
        EmojiItem("📐", ["triangular", "ruler"]),
        EmojiItem("✂️", ["scissors"]),
        EmojiItem("🗃️", ["card", "file", "box"]),
        EmojiItem("🗄️", ["file", "cabinet"]),
        EmojiItem("🗑️", ["wastebasket"]),
        EmojiItem("🔒", ["locked"]),
        EmojiItem("🔓", ["unlocked"]),
        EmojiItem("🔏", ["locked", "with", "pen"]),
        EmojiItem("🔐", ["locked", "with", "key"]),
        EmojiItem("🔑", ["key"]),
        EmojiItem("🗝️", ["old", "key"]),
        EmojiItem("🔨", ["hammer"]),
        EmojiItem("🪓", ["axe"]),
        EmojiItem("⛏️", ["pick"]),
        EmojiItem("⚒️", ["hammer", "and", "pick"]),
        EmojiItem("🛠️", ["hammer", "and", "wrench"]),
        EmojiItem("🗡️", ["dagger"]),
        EmojiItem("⚔️", ["crossed", "swords"]),
        EmojiItem("💣", ["bomb"]),
        EmojiItem("🪃", ["boomerang"]),
        EmojiItem("🏹", ["bow", "and", "arrow"]),
        EmojiItem("🛡️", ["shield"]),
        EmojiItem("🪚", ["carpentry", "saw"]),
        EmojiItem("🔧", ["wrench"]),
        EmojiItem("🪛", ["screwdriver"]),
        EmojiItem("🔩", ["nut", "and", "bolt"]),
        EmojiItem("⚙️", ["gear"]),
        EmojiItem("🗜️", ["clamp"]),
        EmojiItem("⚖️", ["balance", "scale"]),
        EmojiItem("🦯", ["white", "cane"]),
        EmojiItem("🔗", ["link"]),
        EmojiItem("⛓️‍💥", ["broken", "chain"]),
        EmojiItem("⛓️", ["chains"]),
        EmojiItem("🪝", ["hook"]),
        EmojiItem("🧰", ["toolbox"]),
        EmojiItem("🧲", ["magnet"]),
        EmojiItem("🪜", ["ladder"]),
        EmojiItem("⚗️", ["alembic"]),
        EmojiItem("🧪", ["test", "tube"]),
        EmojiItem("🧫", ["petri", "dish"]),
        EmojiItem("🧬", ["dna"]),
        EmojiItem("🔬", ["microscope"]),
        EmojiItem("🔭", ["telescope"]),
        EmojiItem("📡", ["satellite", "antenna"]),
        EmojiItem("💉", ["syringe"]),
        EmojiItem("🩸", ["drop", "of", "blood"]),
        EmojiItem("💊", ["pill"]),
        EmojiItem("🩹", ["adhesive", "bandage"]),
        EmojiItem("🩼", ["crutch"]),
        EmojiItem("🩺", ["stethoscope"]),
        EmojiItem("🩻", ["x", "ray"]),
        EmojiItem("🚪", ["door"]),
        EmojiItem("🛗", ["elevator"]),
        EmojiItem("🪞", ["mirror"]),
        EmojiItem("🪟", ["window"]),
        EmojiItem("🛏️", ["bed"]),
        EmojiItem("🛋️", ["couch", "and", "lamp"]),
        EmojiItem("🪑", ["chair"]),
        EmojiItem("🚽", ["toilet"]),
        EmojiItem("🪠", ["plunger"]),
        EmojiItem("🚿", ["shower"]),
        EmojiItem("🛁", ["bathtub"]),
        EmojiItem("🪤", ["mouse", "trap"]),
        EmojiItem("🪒", ["razor"]),
        EmojiItem("🧴", ["lotion", "bottle"]),
        EmojiItem("🧷", ["safety", "pin"]),
        EmojiItem("🧹", ["broom"]),
        EmojiItem("🧺", ["basket"]),
        EmojiItem("🧻", ["roll", "of", "paper"]),
        EmojiItem("🪣", ["bucket"]),
        EmojiItem("🧼", ["soap"]),
        EmojiItem("🫧", ["bubbles"]),
        EmojiItem("🪥", ["toothbrush"]),
        EmojiItem("🧽", ["sponge"]),
        EmojiItem("🧯", ["fire", "extinguisher"]),
        EmojiItem("🛒", ["shopping", "cart"]),
        EmojiItem("🚬", ["cigarette"]),
        EmojiItem("⚰️", ["coffin"]),
        EmojiItem("🪦", ["headstone"]),
        EmojiItem("⚱️", ["funeral", "urn"]),
        EmojiItem("🧿", ["nazar", "amulet"]),
        EmojiItem("🪬", ["hamsa"]),
        EmojiItem("🗿", ["moai"]),
        EmojiItem("🪧", ["placard"]),
        EmojiItem("🪪", ["identification", "card"]),
    ]

    // MARK: - Symbols (223)
    static let symbols: [EmojiItem] = [
        EmojiItem("🏧", ["atm", "sign"]),
        EmojiItem("🚮", ["litter", "in", "bin", "sign"]),
        EmojiItem("🚰", ["potable", "water"]),
        EmojiItem("♿", ["wheelchair", "symbol"]),
        EmojiItem("🚹", ["men’s", "room"]),
        EmojiItem("🚺", ["women’s", "room"]),
        EmojiItem("🚻", ["restroom"]),
        EmojiItem("🚼", ["baby", "symbol"]),
        EmojiItem("🚾", ["water", "closet"]),
        EmojiItem("🛂", ["passport", "control"]),
        EmojiItem("🛃", ["customs"]),
        EmojiItem("🛄", ["baggage", "claim"]),
        EmojiItem("🛅", ["left", "luggage"]),
        EmojiItem("⚠️", ["warning"]),
        EmojiItem("🚸", ["children", "crossing"]),
        EmojiItem("⛔", ["no", "entry"]),
        EmojiItem("🚫", ["prohibited"]),
        EmojiItem("🚳", ["no", "bicycles"]),
        EmojiItem("🚭", ["no", "smoking"]),
        EmojiItem("🚯", ["no", "littering"]),
        EmojiItem("🚱", ["non", "potable", "water"]),
        EmojiItem("🚷", ["no", "pedestrians"]),
        EmojiItem("📵", ["no", "mobile", "phones"]),
        EmojiItem("🔞", ["no", "one", "under", "eighteen"]),
        EmojiItem("☢️", ["radioactive"]),
        EmojiItem("☣️", ["biohazard"]),
        EmojiItem("⬆️", ["up", "arrow"]),
        EmojiItem("↗️", ["up", "right", "arrow"]),
        EmojiItem("➡️", ["right", "arrow"]),
        EmojiItem("↘️", ["down", "right", "arrow"]),
        EmojiItem("⬇️", ["down", "arrow"]),
        EmojiItem("↙️", ["down", "left", "arrow"]),
        EmojiItem("⬅️", ["left", "arrow"]),
        EmojiItem("↖️", ["up", "left", "arrow"]),
        EmojiItem("↕️", ["up", "down", "arrow"]),
        EmojiItem("↔️", ["left", "right", "arrow"]),
        EmojiItem("↩️", ["right", "arrow", "curving", "left"]),
        EmojiItem("↪️", ["left", "arrow", "curving", "right"]),
        EmojiItem("⤴️", ["right", "arrow", "curving", "up"]),
        EmojiItem("⤵️", ["right", "arrow", "curving", "down"]),
        EmojiItem("🔃", ["clockwise", "vertical", "arrows"]),
        EmojiItem("🔄", ["counterclockwise", "arrows", "button"]),
        EmojiItem("🔙", ["back", "arrow"]),
        EmojiItem("🔚", ["end", "arrow"]),
        EmojiItem("🔛", ["on!", "arrow"]),
        EmojiItem("🔜", ["soon", "arrow"]),
        EmojiItem("🔝", ["top", "arrow"]),
        EmojiItem("🛐", ["place", "of", "worship"]),
        EmojiItem("⚛️", ["atom", "symbol"]),
        EmojiItem("🕉️", ["om"]),
        EmojiItem("✡️", ["star", "of", "david"]),
        EmojiItem("☸️", ["wheel", "of", "dharma"]),
        EmojiItem("☯️", ["yin", "yang"]),
        EmojiItem("✝️", ["latin", "cross"]),
        EmojiItem("☦️", ["orthodox", "cross"]),
        EmojiItem("☪️", ["star", "and", "crescent"]),
        EmojiItem("☮️", ["peace", "symbol"]),
        EmojiItem("🕎", ["menorah"]),
        EmojiItem("🔯", ["dotted", "six", "pointed", "star"]),
        EmojiItem("🪯", ["khanda"]),
        EmojiItem("♈", ["aries"]),
        EmojiItem("♉", ["taurus"]),
        EmojiItem("♊", ["gemini"]),
        EmojiItem("♋", ["cancer"]),
        EmojiItem("♌", ["leo"]),
        EmojiItem("♍", ["virgo"]),
        EmojiItem("♎", ["libra"]),
        EmojiItem("♏", ["scorpio"]),
        EmojiItem("♐", ["sagittarius"]),
        EmojiItem("♑", ["capricorn"]),
        EmojiItem("♒", ["aquarius"]),
        EmojiItem("♓", ["pisces"]),
        EmojiItem("⛎", ["ophiuchus"]),
        EmojiItem("🔀", ["shuffle", "tracks", "button"]),
        EmojiItem("🔁", ["repeat", "button"]),
        EmojiItem("🔂", ["repeat", "single", "button"]),
        EmojiItem("▶️", ["play", "button"]),
        EmojiItem("⏩", ["fast", "forward", "button"]),
        EmojiItem("⏭️", ["next", "track", "button"]),
        EmojiItem("⏯️", ["play", "or", "pause", "button"]),
        EmojiItem("◀️", ["reverse", "button"]),
        EmojiItem("⏪", ["fast", "reverse", "button"]),
        EmojiItem("⏮️", ["last", "track", "button"]),
        EmojiItem("🔼", ["upwards", "button"]),
        EmojiItem("⏫", ["fast", "up", "button"]),
        EmojiItem("🔽", ["downwards", "button"]),
        EmojiItem("⏬", ["fast", "down", "button"]),
        EmojiItem("⏸️", ["pause", "button"]),
        EmojiItem("⏹️", ["stop", "button"]),
        EmojiItem("⏺️", ["record", "button"]),
        EmojiItem("⏏️", ["eject", "button"]),
        EmojiItem("🎦", ["cinema"]),
        EmojiItem("🔅", ["dim", "button"]),
        EmojiItem("🔆", ["bright", "button"]),
        EmojiItem("📶", ["antenna", "bars"]),
        EmojiItem("🛜", ["wireless"]),
        EmojiItem("📳", ["vibration", "mode"]),
        EmojiItem("📴", ["mobile", "phone", "off"]),
        EmojiItem("♀️", ["female", "sign"]),
        EmojiItem("♂️", ["male", "sign"]),
        EmojiItem("⚧️", ["transgender", "symbol"]),
        EmojiItem("✖️", ["multiply"]),
        EmojiItem("➕", ["plus"]),
        EmojiItem("➖", ["minus"]),
        EmojiItem("➗", ["divide"]),
        EmojiItem("🟰", ["heavy", "equals", "sign"]),
        EmojiItem("♾️", ["infinity"]),
        EmojiItem("‼️", ["double", "exclamation", "mark"]),
        EmojiItem("⁉️", ["exclamation", "question", "mark"]),
        EmojiItem("❓", ["red", "question", "mark"]),
        EmojiItem("❔", ["white", "question", "mark"]),
        EmojiItem("❕", ["white", "exclamation", "mark"]),
        EmojiItem("❗", ["red", "exclamation", "mark"]),
        EmojiItem("〰️", ["wavy", "dash"]),
        EmojiItem("💱", ["currency", "exchange"]),
        EmojiItem("💲", ["heavy", "dollar", "sign"]),
        EmojiItem("⚕️", ["medical", "symbol"]),
        EmojiItem("♻️", ["recycling", "symbol"]),
        EmojiItem("⚜️", ["fleur", "de", "lis"]),
        EmojiItem("🔱", ["trident", "emblem"]),
        EmojiItem("📛", ["name", "badge"]),
        EmojiItem("🔰", ["japanese", "symbol", "for", "beginner"]),
        EmojiItem("⭕", ["hollow", "red", "circle"]),
        EmojiItem("✅", ["check", "mark", "button"]),
        EmojiItem("☑️", ["check", "box", "with", "check"]),
        EmojiItem("✔️", ["check", "mark"]),
        EmojiItem("❌", ["cross", "mark"]),
        EmojiItem("❎", ["cross", "mark", "button"]),
        EmojiItem("➰", ["curly", "loop"]),
        EmojiItem("➿", ["double", "curly", "loop"]),
        EmojiItem("〽️", ["part", "alternation", "mark"]),
        EmojiItem("✳️", ["eight", "spoked", "asterisk"]),
        EmojiItem("✴️", ["eight", "pointed", "star"]),
        EmojiItem("❇️", ["sparkle"]),
        EmojiItem("©️", ["copyright"]),
        EmojiItem("®️", ["registered"]),
        EmojiItem("™️", ["trade", "mark"]),
        EmojiItem("#️⃣", ["keycap", "#"]),
        EmojiItem("*️⃣", ["keycap", "*"]),
        EmojiItem("0️⃣", ["keycap", "0"]),
        EmojiItem("1️⃣", ["keycap", "1"]),
        EmojiItem("2️⃣", ["keycap", "2"]),
        EmojiItem("3️⃣", ["keycap", "3"]),
        EmojiItem("4️⃣", ["keycap", "4"]),
        EmojiItem("5️⃣", ["keycap", "5"]),
        EmojiItem("6️⃣", ["keycap", "6"]),
        EmojiItem("7️⃣", ["keycap", "7"]),
        EmojiItem("8️⃣", ["keycap", "8"]),
        EmojiItem("9️⃣", ["keycap", "9"]),
        EmojiItem("🔟", ["keycap", "10"]),
        EmojiItem("🔠", ["input", "latin", "uppercase"]),
        EmojiItem("🔡", ["input", "latin", "lowercase"]),
        EmojiItem("🔢", ["input", "numbers"]),
        EmojiItem("🔣", ["input", "symbols"]),
        EmojiItem("🔤", ["input", "latin", "letters"]),
        EmojiItem("🅰️", ["a", "button", "(blood", "type)"]),
        EmojiItem("🆎", ["ab", "button", "(blood", "type)"]),
        EmojiItem("🅱️", ["b", "button", "(blood", "type)"]),
        EmojiItem("🆑", ["cl", "button"]),
        EmojiItem("🆒", ["cool", "button"]),
        EmojiItem("🆓", ["free", "button"]),
        EmojiItem("ℹ️", ["information"]),
        EmojiItem("🆔", ["id", "button"]),
        EmojiItem("Ⓜ️", ["circled", "m"]),
        EmojiItem("🆕", ["new", "button"]),
        EmojiItem("🆖", ["ng", "button"]),
        EmojiItem("🅾️", ["o", "button", "(blood", "type)"]),
        EmojiItem("🆗", ["ok", "button"]),
        EmojiItem("🅿️", ["p", "button"]),
        EmojiItem("🆘", ["sos", "button"]),
        EmojiItem("🆙", ["up!", "button"]),
        EmojiItem("🆚", ["vs", "button"]),
        EmojiItem("🈁", ["japanese", "“here”", "button"]),
        EmojiItem("🈂️", ["japanese", "“service", "charge”", "button"]),
        EmojiItem("🈷️", ["japanese", "“monthly", "amount”", "button"]),
        EmojiItem("🈶", ["japanese", "“not", "free", "of", "charge”", "button"]),
        EmojiItem("🈯", ["japanese", "“reserved”", "button"]),
        EmojiItem("🉐", ["japanese", "“bargain”", "button"]),
        EmojiItem("🈹", ["japanese", "“discount”", "button"]),
        EmojiItem("🈚", ["japanese", "“free", "of", "charge”", "button"]),
        EmojiItem("🈲", ["japanese", "“prohibited”", "button"]),
        EmojiItem("🉑", ["japanese", "“acceptable”", "button"]),
        EmojiItem("🈸", ["japanese", "“application”", "button"]),
        EmojiItem("🈴", ["japanese", "“passing", "grade”", "button"]),
        EmojiItem("🈳", ["japanese", "“vacancy”", "button"]),
        EmojiItem("㊗️", ["japanese", "“congratulations”", "button"]),
        EmojiItem("㊙️", ["japanese", "“secret”", "button"]),
        EmojiItem("🈺", ["japanese", "“open", "for", "business”", "button"]),
        EmojiItem("🈵", ["japanese", "“no", "vacancy”", "button"]),
        EmojiItem("🔴", ["red", "circle"]),
        EmojiItem("🟠", ["orange", "circle"]),
        EmojiItem("🟡", ["yellow", "circle"]),
        EmojiItem("🟢", ["green", "circle"]),
        EmojiItem("🔵", ["blue", "circle"]),
        EmojiItem("🟣", ["purple", "circle"]),
        EmojiItem("🟤", ["brown", "circle"]),
        EmojiItem("⚫", ["black", "circle"]),
        EmojiItem("⚪", ["white", "circle"]),
        EmojiItem("🟥", ["red", "square"]),
        EmojiItem("🟧", ["orange", "square"]),
        EmojiItem("🟨", ["yellow", "square"]),
        EmojiItem("🟩", ["green", "square"]),
        EmojiItem("🟦", ["blue", "square"]),
        EmojiItem("🟪", ["purple", "square"]),
        EmojiItem("🟫", ["brown", "square"]),
        EmojiItem("⬛", ["black", "large", "square"]),
        EmojiItem("⬜", ["white", "large", "square"]),
        EmojiItem("◼️", ["black", "medium", "square"]),
        EmojiItem("◻️", ["white", "medium", "square"]),
        EmojiItem("◾", ["black", "medium", "small", "square"]),
        EmojiItem("◽", ["white", "medium", "small", "square"]),
        EmojiItem("▪️", ["black", "small", "square"]),
        EmojiItem("▫️", ["white", "small", "square"]),
        EmojiItem("🔶", ["large", "orange", "diamond"]),
        EmojiItem("🔷", ["large", "blue", "diamond"]),
        EmojiItem("🔸", ["small", "orange", "diamond"]),
        EmojiItem("🔹", ["small", "blue", "diamond"]),
        EmojiItem("🔺", ["red", "triangle", "pointed", "up"]),
        EmojiItem("🔻", ["red", "triangle", "pointed", "down"]),
        EmojiItem("💠", ["diamond", "with", "a", "dot"]),
        EmojiItem("🔘", ["radio", "button"]),
        EmojiItem("🔳", ["white", "square", "button"]),
        EmojiItem("🔲", ["black", "square", "button"]),
    ]

    // MARK: - Flags (269)
    static let flags: [EmojiItem] = [
        EmojiItem("🏁", ["chequered", "flag"]),
        EmojiItem("🚩", ["triangular", "flag"]),
        EmojiItem("🎌", ["crossed", "flags"]),
        EmojiItem("🏴", ["black", "flag"]),
        EmojiItem("🏳️", ["white", "flag"]),
        EmojiItem("🏳️‍🌈", ["rainbow", "flag"]),
        EmojiItem("🏳️‍⚧️", ["transgender", "flag"]),
        EmojiItem("🏴‍☠️", ["pirate", "flag"]),
        EmojiItem("🇦🇨", ["flag", "ascension", "island"]),
        EmojiItem("🇦🇩", ["flag", "andorra"]),
        EmojiItem("🇦🇪", ["flag", "united", "arab", "emirates"]),
        EmojiItem("🇦🇫", ["flag", "afghanistan"]),
        EmojiItem("🇦🇬", ["flag", "antigua", "&", "barbuda"]),
        EmojiItem("🇦🇮", ["flag", "anguilla"]),
        EmojiItem("🇦🇱", ["flag", "albania"]),
        EmojiItem("🇦🇲", ["flag", "armenia"]),
        EmojiItem("🇦🇴", ["flag", "angola"]),
        EmojiItem("🇦🇶", ["flag", "antarctica"]),
        EmojiItem("🇦🇷", ["flag", "argentina"]),
        EmojiItem("🇦🇸", ["flag", "american", "samoa"]),
        EmojiItem("🇦🇹", ["flag", "austria"]),
        EmojiItem("🇦🇺", ["flag", "australia"]),
        EmojiItem("🇦🇼", ["flag", "aruba"]),
        EmojiItem("🇦🇽", ["flag", "åland", "islands"]),
        EmojiItem("🇦🇿", ["flag", "azerbaijan"]),
        EmojiItem("🇧🇦", ["flag", "bosnia", "&", "herzegovina"]),
        EmojiItem("🇧🇧", ["flag", "barbados"]),
        EmojiItem("🇧🇩", ["flag", "bangladesh"]),
        EmojiItem("🇧🇪", ["flag", "belgium"]),
        EmojiItem("🇧🇫", ["flag", "burkina", "faso"]),
        EmojiItem("🇧🇬", ["flag", "bulgaria"]),
        EmojiItem("🇧🇭", ["flag", "bahrain"]),
        EmojiItem("🇧🇮", ["flag", "burundi"]),
        EmojiItem("🇧🇯", ["flag", "benin"]),
        EmojiItem("🇧🇱", ["flag", "st.", "barthélemy"]),
        EmojiItem("🇧🇲", ["flag", "bermuda"]),
        EmojiItem("🇧🇳", ["flag", "brunei"]),
        EmojiItem("🇧🇴", ["flag", "bolivia"]),
        EmojiItem("🇧🇶", ["flag", "caribbean", "netherlands"]),
        EmojiItem("🇧🇷", ["flag", "brazil"]),
        EmojiItem("🇧🇸", ["flag", "bahamas"]),
        EmojiItem("🇧🇹", ["flag", "bhutan"]),
        EmojiItem("🇧🇻", ["flag", "bouvet", "island"]),
        EmojiItem("🇧🇼", ["flag", "botswana"]),
        EmojiItem("🇧🇾", ["flag", "belarus"]),
        EmojiItem("🇧🇿", ["flag", "belize"]),
        EmojiItem("🇨🇦", ["flag", "canada"]),
        EmojiItem("🇨🇨", ["flag", "cocos", "(keeling)", "islands"]),
        EmojiItem("🇨🇩", ["flag", "congo", "kinshasa"]),
        EmojiItem("🇨🇫", ["flag", "central", "african", "republic"]),
        EmojiItem("🇨🇬", ["flag", "congo", "brazzaville"]),
        EmojiItem("🇨🇭", ["flag", "switzerland"]),
        EmojiItem("🇨🇮", ["flag", "côte", "d’ivoire"]),
        EmojiItem("🇨🇰", ["flag", "cook", "islands"]),
        EmojiItem("🇨🇱", ["flag", "chile"]),
        EmojiItem("🇨🇲", ["flag", "cameroon"]),
        EmojiItem("🇨🇳", ["flag", "china"]),
        EmojiItem("🇨🇴", ["flag", "colombia"]),
        EmojiItem("🇨🇵", ["flag", "clipperton", "island"]),
        EmojiItem("🇨🇷", ["flag", "costa", "rica"]),
        EmojiItem("🇨🇺", ["flag", "cuba"]),
        EmojiItem("🇨🇻", ["flag", "cape", "verde"]),
        EmojiItem("🇨🇼", ["flag", "curaçao"]),
        EmojiItem("🇨🇽", ["flag", "christmas", "island"]),
        EmojiItem("🇨🇾", ["flag", "cyprus"]),
        EmojiItem("🇨🇿", ["flag", "czechia"]),
        EmojiItem("🇩🇪", ["flag", "germany"]),
        EmojiItem("🇩🇬", ["flag", "diego", "garcia"]),
        EmojiItem("🇩🇯", ["flag", "djibouti"]),
        EmojiItem("🇩🇰", ["flag", "denmark"]),
        EmojiItem("🇩🇲", ["flag", "dominica"]),
        EmojiItem("🇩🇴", ["flag", "dominican", "republic"]),
        EmojiItem("🇩🇿", ["flag", "algeria"]),
        EmojiItem("🇪🇦", ["flag", "ceuta", "&", "melilla"]),
        EmojiItem("🇪🇨", ["flag", "ecuador"]),
        EmojiItem("🇪🇪", ["flag", "estonia"]),
        EmojiItem("🇪🇬", ["flag", "egypt"]),
        EmojiItem("🇪🇭", ["flag", "western", "sahara"]),
        EmojiItem("🇪🇷", ["flag", "eritrea"]),
        EmojiItem("🇪🇸", ["flag", "spain"]),
        EmojiItem("🇪🇹", ["flag", "ethiopia"]),
        EmojiItem("🇪🇺", ["flag", "european", "union"]),
        EmojiItem("🇫🇮", ["flag", "finland"]),
        EmojiItem("🇫🇯", ["flag", "fiji"]),
        EmojiItem("🇫🇰", ["flag", "falkland", "islands"]),
        EmojiItem("🇫🇲", ["flag", "micronesia"]),
        EmojiItem("🇫🇴", ["flag", "faroe", "islands"]),
        EmojiItem("🇫🇷", ["flag", "france"]),
        EmojiItem("🇬🇦", ["flag", "gabon"]),
        EmojiItem("🇬🇧", ["flag", "united", "kingdom"]),
        EmojiItem("🇬🇩", ["flag", "grenada"]),
        EmojiItem("🇬🇪", ["flag", "georgia"]),
        EmojiItem("🇬🇫", ["flag", "french", "guiana"]),
        EmojiItem("🇬🇬", ["flag", "guernsey"]),
        EmojiItem("🇬🇭", ["flag", "ghana"]),
        EmojiItem("🇬🇮", ["flag", "gibraltar"]),
        EmojiItem("🇬🇱", ["flag", "greenland"]),
        EmojiItem("🇬🇲", ["flag", "gambia"]),
        EmojiItem("🇬🇳", ["flag", "guinea"]),
        EmojiItem("🇬🇵", ["flag", "guadeloupe"]),
        EmojiItem("🇬🇶", ["flag", "equatorial", "guinea"]),
        EmojiItem("🇬🇷", ["flag", "greece"]),
        EmojiItem("🇬🇸", ["flag", "south", "georgia", "&", "south", "sandwich", "islands"]),
        EmojiItem("🇬🇹", ["flag", "guatemala"]),
        EmojiItem("🇬🇺", ["flag", "guam"]),
        EmojiItem("🇬🇼", ["flag", "guinea", "bissau"]),
        EmojiItem("🇬🇾", ["flag", "guyana"]),
        EmojiItem("🇭🇰", ["flag", "hong", "kong", "sar", "china"]),
        EmojiItem("🇭🇲", ["flag", "heard", "&", "mcdonald", "islands"]),
        EmojiItem("🇭🇳", ["flag", "honduras"]),
        EmojiItem("🇭🇷", ["flag", "croatia"]),
        EmojiItem("🇭🇹", ["flag", "haiti"]),
        EmojiItem("🇭🇺", ["flag", "hungary"]),
        EmojiItem("🇮🇨", ["flag", "canary", "islands"]),
        EmojiItem("🇮🇩", ["flag", "indonesia"]),
        EmojiItem("🇮🇪", ["flag", "ireland"]),
        EmojiItem("🇮🇱", ["flag", "israel"]),
        EmojiItem("🇮🇲", ["flag", "isle", "of", "man"]),
        EmojiItem("🇮🇳", ["flag", "india"]),
        EmojiItem("🇮🇴", ["flag", "british", "indian", "ocean", "territory"]),
        EmojiItem("🇮🇶", ["flag", "iraq"]),
        EmojiItem("🇮🇷", ["flag", "iran"]),
        EmojiItem("🇮🇸", ["flag", "iceland"]),
        EmojiItem("🇮🇹", ["flag", "italy"]),
        EmojiItem("🇯🇪", ["flag", "jersey"]),
        EmojiItem("🇯🇲", ["flag", "jamaica"]),
        EmojiItem("🇯🇴", ["flag", "jordan"]),
        EmojiItem("🇯🇵", ["flag", "japan"]),
        EmojiItem("🇰🇪", ["flag", "kenya"]),
        EmojiItem("🇰🇬", ["flag", "kyrgyzstan"]),
        EmojiItem("🇰🇭", ["flag", "cambodia"]),
        EmojiItem("🇰🇮", ["flag", "kiribati"]),
        EmojiItem("🇰🇲", ["flag", "comoros"]),
        EmojiItem("🇰🇳", ["flag", "st.", "kitts", "&", "nevis"]),
        EmojiItem("🇰🇵", ["flag", "north", "korea"]),
        EmojiItem("🇰🇷", ["flag", "south", "korea"]),
        EmojiItem("🇰🇼", ["flag", "kuwait"]),
        EmojiItem("🇰🇾", ["flag", "cayman", "islands"]),
        EmojiItem("🇰🇿", ["flag", "kazakhstan"]),
        EmojiItem("🇱🇦", ["flag", "laos"]),
        EmojiItem("🇱🇧", ["flag", "lebanon"]),
        EmojiItem("🇱🇨", ["flag", "st.", "lucia"]),
        EmojiItem("🇱🇮", ["flag", "liechtenstein"]),
        EmojiItem("🇱🇰", ["flag", "sri", "lanka"]),
        EmojiItem("🇱🇷", ["flag", "liberia"]),
        EmojiItem("🇱🇸", ["flag", "lesotho"]),
        EmojiItem("🇱🇹", ["flag", "lithuania"]),
        EmojiItem("🇱🇺", ["flag", "luxembourg"]),
        EmojiItem("🇱🇻", ["flag", "latvia"]),
        EmojiItem("🇱🇾", ["flag", "libya"]),
        EmojiItem("🇲🇦", ["flag", "morocco"]),
        EmojiItem("🇲🇨", ["flag", "monaco"]),
        EmojiItem("🇲🇩", ["flag", "moldova"]),
        EmojiItem("🇲🇪", ["flag", "montenegro"]),
        EmojiItem("🇲🇫", ["flag", "st.", "martin"]),
        EmojiItem("🇲🇬", ["flag", "madagascar"]),
        EmojiItem("🇲🇭", ["flag", "marshall", "islands"]),
        EmojiItem("🇲🇰", ["flag", "north", "macedonia"]),
        EmojiItem("🇲🇱", ["flag", "mali"]),
        EmojiItem("🇲🇲", ["flag", "myanmar", "(burma)"]),
        EmojiItem("🇲🇳", ["flag", "mongolia"]),
        EmojiItem("🇲🇴", ["flag", "macao", "sar", "china"]),
        EmojiItem("🇲🇵", ["flag", "northern", "mariana", "islands"]),
        EmojiItem("🇲🇶", ["flag", "martinique"]),
        EmojiItem("🇲🇷", ["flag", "mauritania"]),
        EmojiItem("🇲🇸", ["flag", "montserrat"]),
        EmojiItem("🇲🇹", ["flag", "malta"]),
        EmojiItem("🇲🇺", ["flag", "mauritius"]),
        EmojiItem("🇲🇻", ["flag", "maldives"]),
        EmojiItem("🇲🇼", ["flag", "malawi"]),
        EmojiItem("🇲🇽", ["flag", "mexico"]),
        EmojiItem("🇲🇾", ["flag", "malaysia"]),
        EmojiItem("🇲🇿", ["flag", "mozambique"]),
        EmojiItem("🇳🇦", ["flag", "namibia"]),
        EmojiItem("🇳🇨", ["flag", "new", "caledonia"]),
        EmojiItem("🇳🇪", ["flag", "niger"]),
        EmojiItem("🇳🇫", ["flag", "norfolk", "island"]),
        EmojiItem("🇳🇬", ["flag", "nigeria"]),
        EmojiItem("🇳🇮", ["flag", "nicaragua"]),
        EmojiItem("🇳🇱", ["flag", "netherlands"]),
        EmojiItem("🇳🇴", ["flag", "norway"]),
        EmojiItem("🇳🇵", ["flag", "nepal"]),
        EmojiItem("🇳🇷", ["flag", "nauru"]),
        EmojiItem("🇳🇺", ["flag", "niue"]),
        EmojiItem("🇳🇿", ["flag", "new", "zealand"]),
        EmojiItem("🇴🇲", ["flag", "oman"]),
        EmojiItem("🇵🇦", ["flag", "panama"]),
        EmojiItem("🇵🇪", ["flag", "peru"]),
        EmojiItem("🇵🇫", ["flag", "french", "polynesia"]),
        EmojiItem("🇵🇬", ["flag", "papua", "new", "guinea"]),
        EmojiItem("🇵🇭", ["flag", "philippines"]),
        EmojiItem("🇵🇰", ["flag", "pakistan"]),
        EmojiItem("🇵🇱", ["flag", "poland"]),
        EmojiItem("🇵🇲", ["flag", "st.", "pierre", "&", "miquelon"]),
        EmojiItem("🇵🇳", ["flag", "pitcairn", "islands"]),
        EmojiItem("🇵🇷", ["flag", "puerto", "rico"]),
        EmojiItem("🇵🇸", ["flag", "palestinian", "territories"]),
        EmojiItem("🇵🇹", ["flag", "portugal"]),
        EmojiItem("🇵🇼", ["flag", "palau"]),
        EmojiItem("🇵🇾", ["flag", "paraguay"]),
        EmojiItem("🇶🇦", ["flag", "qatar"]),
        EmojiItem("🇷🇪", ["flag", "réunion"]),
        EmojiItem("🇷🇴", ["flag", "romania"]),
        EmojiItem("🇷🇸", ["flag", "serbia"]),
        EmojiItem("🇷🇺", ["flag", "russia"]),
        EmojiItem("🇷🇼", ["flag", "rwanda"]),
        EmojiItem("🇸🇦", ["flag", "saudi", "arabia"]),
        EmojiItem("🇸🇧", ["flag", "solomon", "islands"]),
        EmojiItem("🇸🇨", ["flag", "seychelles"]),
        EmojiItem("🇸🇩", ["flag", "sudan"]),
        EmojiItem("🇸🇪", ["flag", "sweden"]),
        EmojiItem("🇸🇬", ["flag", "singapore"]),
        EmojiItem("🇸🇭", ["flag", "st.", "helena"]),
        EmojiItem("🇸🇮", ["flag", "slovenia"]),
        EmojiItem("🇸🇯", ["flag", "svalbard", "&", "jan", "mayen"]),
        EmojiItem("🇸🇰", ["flag", "slovakia"]),
        EmojiItem("🇸🇱", ["flag", "sierra", "leone"]),
        EmojiItem("🇸🇲", ["flag", "san", "marino"]),
        EmojiItem("🇸🇳", ["flag", "senegal"]),
        EmojiItem("🇸🇴", ["flag", "somalia"]),
        EmojiItem("🇸🇷", ["flag", "suriname"]),
        EmojiItem("🇸🇸", ["flag", "south", "sudan"]),
        EmojiItem("🇸🇹", ["flag", "são", "tomé", "&", "príncipe"]),
        EmojiItem("🇸🇻", ["flag", "el", "salvador"]),
        EmojiItem("🇸🇽", ["flag", "sint", "maarten"]),
        EmojiItem("🇸🇾", ["flag", "syria"]),
        EmojiItem("🇸🇿", ["flag", "eswatini"]),
        EmojiItem("🇹🇦", ["flag", "tristan", "da", "cunha"]),
        EmojiItem("🇹🇨", ["flag", "turks", "&", "caicos", "islands"]),
        EmojiItem("🇹🇩", ["flag", "chad"]),
        EmojiItem("🇹🇫", ["flag", "french", "southern", "territories"]),
        EmojiItem("🇹🇬", ["flag", "togo"]),
        EmojiItem("🇹🇭", ["flag", "thailand"]),
        EmojiItem("🇹🇯", ["flag", "tajikistan"]),
        EmojiItem("🇹🇰", ["flag", "tokelau"]),
        EmojiItem("🇹🇱", ["flag", "timor", "leste"]),
        EmojiItem("🇹🇲", ["flag", "turkmenistan"]),
        EmojiItem("🇹🇳", ["flag", "tunisia"]),
        EmojiItem("🇹🇴", ["flag", "tonga"]),
        EmojiItem("🇹🇷", ["flag", "türkiye"]),
        EmojiItem("🇹🇹", ["flag", "trinidad", "&", "tobago"]),
        EmojiItem("🇹🇻", ["flag", "tuvalu"]),
        EmojiItem("🇹🇼", ["flag", "taiwan"]),
        EmojiItem("🇹🇿", ["flag", "tanzania"]),
        EmojiItem("🇺🇦", ["flag", "ukraine"]),
        EmojiItem("🇺🇬", ["flag", "uganda"]),
        EmojiItem("🇺🇲", ["flag", "u.s.", "outlying", "islands"]),
        EmojiItem("🇺🇳", ["flag", "united", "nations"]),
        EmojiItem("🇺🇸", ["flag", "united", "states"]),
        EmojiItem("🇺🇾", ["flag", "uruguay"]),
        EmojiItem("🇺🇿", ["flag", "uzbekistan"]),
        EmojiItem("🇻🇦", ["flag", "vatican", "city"]),
        EmojiItem("🇻🇨", ["flag", "st.", "vincent", "&", "grenadines"]),
        EmojiItem("🇻🇪", ["flag", "venezuela"]),
        EmojiItem("🇻🇬", ["flag", "british", "virgin", "islands"]),
        EmojiItem("🇻🇮", ["flag", "u.s.", "virgin", "islands"]),
        EmojiItem("🇻🇳", ["flag", "vietnam"]),
        EmojiItem("🇻🇺", ["flag", "vanuatu"]),
        EmojiItem("🇼🇫", ["flag", "wallis", "&", "futuna"]),
        EmojiItem("🇼🇸", ["flag", "samoa"]),
        EmojiItem("🇽🇰", ["flag", "kosovo"]),
        EmojiItem("🇾🇪", ["flag", "yemen"]),
        EmojiItem("🇾🇹", ["flag", "mayotte"]),
        EmojiItem("🇿🇦", ["flag", "south", "africa"]),
        EmojiItem("🇿🇲", ["flag", "zambia"]),
        EmojiItem("🇿🇼", ["flag", "zimbabwe"]),
        EmojiItem("🏴󠁧󠁢󠁥󠁮󠁧󠁿", ["flag", "england"]),
        EmojiItem("🏴󠁧󠁢󠁳󠁣󠁴󠁿", ["flag", "scotland"]),
        EmojiItem("🏴󠁧󠁢󠁷󠁬󠁳󠁿", ["flag", "wales"]),
    ]

}
