import Foundation

struct EmojiCategory: Identifiable {
    let id: String
    let name: String
    let icon: String
    let emojis: [EmojiItem]
}

struct EmojiItem: Identifiable {
    let id: String
    let emoji: String
    let keywords: [String]

    init(_ emoji: String, _ keywords: [String] = []) {
        self.id = emoji
        self.emoji = emoji
        self.keywords = keywords
    }
}

enum EmojiData {
    static let defaultQuickReactions = ["👍", "❤️", "😂", "😮", "😢", "🙏"]

    static let categories: [EmojiCategory] = [
        EmojiCategory(id: "recent", name: "Recent", icon: "clock", emojis: []),
        EmojiCategory(id: "smileys", name: "Smileys & People", icon: "face.smiling", emojis: smileys),
        EmojiCategory(id: "animals", name: "Animals & Nature", icon: "hare", emojis: animals),
        EmojiCategory(id: "food", name: "Food & Drink", icon: "fork.knife", emojis: food),
        EmojiCategory(id: "travel", name: "Travel & Places", icon: "car", emojis: travel),
        EmojiCategory(id: "activities", name: "Activities", icon: "sportscourt", emojis: activities),
        EmojiCategory(id: "objects", name: "Objects", icon: "lightbulb", emojis: objects),
        EmojiCategory(id: "symbols", name: "Symbols", icon: "heart", emojis: symbols),
        EmojiCategory(id: "flags", name: "Flags", icon: "flag", emojis: flags),
    ]

    static func search(_ query: String) -> [EmojiItem] {
        let q = query.lowercased()
        var seen = Set<String>()
        return categories.flatMap(\.emojis).filter { item in
            guard !seen.contains(item.emoji) else { return false }
            let matches = item.emoji.contains(q) || item.keywords.contains { $0.contains(q) }
            if matches { seen.insert(item.emoji) }
            return matches
        }
    }

    // MARK: - Smileys & People (~120)
    static let smileys: [EmojiItem] = [
        // Positive faces
        EmojiItem("😀", ["grinning", "happy", "smile", "grin"]),
        EmojiItem("😃", ["smiley", "happy", "smile", "big eyes"]),
        EmojiItem("😄", ["smile", "happy", "grinning", "laugh"]),
        EmojiItem("😁", ["grinning", "happy", "teeth", "grin"]),
        EmojiItem("😆", ["laughing", "happy", "satisfied", "lol"]),
        EmojiItem("😅", ["sweat smile", "nervous", "awkward", "phew"]),
        EmojiItem("🤣", ["rolling on floor", "rofl", "laughing", "lol"]),
        EmojiItem("😂", ["joy", "crying laughing", "tears", "funny", "lol"]),
        EmojiItem("🙂", ["slightly smiling", "smile", "happy"]),
        EmojiItem("🙃", ["upside down", "silly", "sarcasm"]),
        EmojiItem("😉", ["winking", "flirty", "hint"]),
        EmojiItem("😊", ["blushing", "happy", "smile", "warm"]),
        EmojiItem("😇", ["halo", "angel", "innocent", "holy"]),
        EmojiItem("🥰", ["smiling hearts", "love", "adore", "crush"]),
        EmojiItem("😍", ["heart eyes", "love", "adore", "beautiful"]),
        EmojiItem("🤩", ["star struck", "amazed", "starstruck", "wow"]),
        EmojiItem("😘", ["kiss", "blowing kiss", "love", "mwah"]),
        EmojiItem("😗", ["kissing", "kiss", "smooch"]),
        EmojiItem("☺️", ["smiling", "happy", "blush"]),
        EmojiItem("😚", ["kissing closed eyes", "kiss", "love"]),
        EmojiItem("😙", ["kissing smiling eyes", "kiss", "smile"]),
        EmojiItem("🥲", ["smiling tear", "happy cry", "bittersweet"]),
        // Neutral/tongue
        EmojiItem("😋", ["yum", "delicious", "tasty", "tongue"]),
        EmojiItem("😛", ["tongue", "playful", "silly"]),
        EmojiItem("😜", ["winking tongue", "playful", "silly", "crazy"]),
        EmojiItem("🤪", ["zany", "crazy", "wild", "wacky"]),
        EmojiItem("😝", ["squinting tongue", "gross", "taste"]),
        EmojiItem("🤑", ["money mouth", "rich", "dollar", "greedy"]),
        EmojiItem("🤗", ["hugging", "hug", "warm", "embrace"]),
        EmojiItem("🤭", ["hand over mouth", "oops", "secret", "hehe"]),
        EmojiItem("🫢", ["eyes peeking", "shocked", "surprised"]),
        EmojiItem("🫣", ["peeking eye", "sneaky", "peek"]),
        EmojiItem("🤫", ["shushing", "quiet", "secret", "shhh"]),
        EmojiItem("🤔", ["thinking", "hmm", "pondering", "wonder"]),
        EmojiItem("🫡", ["salute", "respect", "yes sir"]),
        // Negative faces
        EmojiItem("🤐", ["zipper mouth", "silent", "quiet", "sealed lips"]),
        EmojiItem("🤨", ["raised eyebrow", "suspicious", "skeptical"]),
        EmojiItem("😐", ["neutral", "expressionless", "meh"]),
        EmojiItem("😑", ["expressionless", "blank", "deadpan"]),
        EmojiItem("😶", ["no mouth", "silent", "speechless"]),
        EmojiItem("🫥", ["dotted line face", "invisible", "ghost"]),
        EmojiItem("😶‍🌫️", ["face in clouds", "lost", "confused"]),
        EmojiItem("😏", ["smirking", "smug", "sly", "sneaky"]),
        EmojiItem("😒", ["unamused", "skeptical", "side eye"]),
        EmojiItem("🙄", ["eye roll", "whatever", "bored", "annoyed"]),
        EmojiItem("😬", ["grimacing", "awkward", "oops", "nervous"]),
        EmojiItem("😮‍💨", ["exhale", "sigh", "relieved", "phew"]),
        EmojiItem("🤥", ["lying", "pinocchio", "fibbing"]),
        EmojiItem("🫨", ["shaking", "trembling", "unbelievable"]),
        EmojiItem("😌", ["relieved", "content", "peaceful"]),
        EmojiItem("😔", ["pensive", "sad", "thoughtful"]),
        EmojiItem("😪", ["sleepy", "tired", "drool"]),
        EmojiItem("🤤", ["drooling", "yummy", "hungry", "sleepy"]),
        EmojiItem("😴", ["sleeping", "zzz", "asleep", "tired"]),
        EmojiItem("😷", ["mask", "sick", "medical", "covid"]),
        EmojiItem("🤒", ["thermometer", "sick", "fever", "ill"]),
        EmojiItem("🤕", ["bandage", "hurt", "injured", "ouch"]),
        EmojiItem("🤢", ["nauseated", "sick", "gross", "eww"]),
        EmojiItem("🤮", ["vomiting", "sick", "gross", "throwing up"]),
        EmojiItem("🤧", ["sneezing", "sick", "tissue", "achoo"]),
        EmojiItem("🥵", ["hot face", "sweating", "overheating", "hot"]),
        EmojiItem("🥶", ["cold face", "freezing", "chilly"]),
        EmojiItem("🥴", ["woozy", "drunk", "dizzy", "tipsy"]),
        EmojiItem("😵", ["dizzy", "dead", "x eyes", "knocked out"]),
        EmojiItem("😵‍💫", ["spiral eyes", "dizzy", "hypnotized"]),
        EmojiItem("🤯", ["mind blown", "exploding head", "shocked", "wow"]),
        EmojiItem("🤠", ["cowboy", "western", "hat", "yeehaw"]),
        EmojiItem("🥳", ["party", "celebrate", "birthday", "confetti"]),
        EmojiItem("🥸", ["disguise", "glasses", "incognito", "spy"]),
        EmojiItem("😎", ["sunglasses", "cool", "awesome", "chill"]),
        EmojiItem("🤓", ["nerd", "glasses", "smart", "geek"]),
        EmojiItem("🧐", ["monocle", "curious", "posh", "inspect"]),
        EmojiItem("😕", ["confused", "unsure", "sad", "hmm"]),
        EmojiItem("🫤", ["diagonal mouth", "meh", "uncertain"]),
        EmojiItem("😟", ["worried", "concerned", "sad"]),
        EmojiItem("🙁", ["slightly frowning", "sad", "unhappy"]),
        EmojiItem("☹️", ["frowning", "sad", "unhappy"]),
        EmojiItem("😮", ["open mouth", "wow", "surprised", "oh"]),
        EmojiItem("😯", ["hushed", "surprised", "shocked"]),
        EmojiItem("😲", ["astonished", "shocked", "wow", "amazed"]),
        EmojiItem("😳", ["flushed", "embarrassed", "shocked", "blushing"]),
        EmojiItem("🥺", ["pleading", "puppy eyes", "begging", "please"]),
        EmojiItem("🥹", ["holding back tears", "grateful", "moved"]),
        EmojiItem("😦", ["frowning open mouth", "sad", "shocked"]),
        EmojiItem("😧", ["anguished", "distressed", "upset"]),
        EmojiItem("😨", ["fearful", "scared", "afraid"]),
        EmojiItem("😰", ["anxious sweat", "nervous", "worried"]),
        EmojiItem("😥", ["sad relieved", "disappointed", "sweat"]),
        EmojiItem("😢", ["crying", "sad", "tear", "unhappy"]),
        EmojiItem("😭", ["loudly crying", "sob", "bawling", "sad"]),
        EmojiItem("😱", ["screaming", "scared", "horror", "shocked"]),
        EmojiItem("😖", ["confounded", "frustrated", "stressed"]),
        EmojiItem("😣", ["persevering", "struggling", "tired"]),
        EmojiItem("😞", ["disappointed", "sad", "let down"]),
        EmojiItem("😓", ["downcast sweat", "hard work", "effort"]),
        EmojiItem("😩", ["weary", "tired", "exhausted"]),
        EmojiItem("😫", ["tired", "exhausted", "dead"]),
        EmojiItem("🥱", ["yawning", "tired", "bored", "sleepy"]),
        EmojiItem("😤", ["triumph", "huffing", "angry", "fuming"]),
        EmojiItem("😡", ["pouting", "angry", "mad", "rage"]),
        EmojiItem("😠", ["angry", "mad", "furious"]),
        EmojiItem("🤬", ["cursing", "angry", "swearing", "rage"]),
        EmojiItem("😈", ["devil grin", "evil", "mischievous", "imp"]),
        EmojiItem("👿", ["angry devil", "evil", "bad"]),
        EmojiItem("💀", ["skull", "dead", "death", "bones"]),
        EmojiItem("☠️", ["skull crossbones", "poison", "danger", "death"]),
        EmojiItem("💩", ["poop", "pile of poo", "crap", "funny"]),
        EmojiItem("🤡", ["clown", "joker", "silly", "circus"]),
        EmojiItem("👹", ["ogre", "monster", "demon", "oni"]),
        EmojiItem("👺", ["goblin", "demon", "tengu", "angry"]),
        EmojiItem("👻", ["ghost", "spooky", "halloween", "boo"]),
        EmojiItem("👽", ["alien", "ufo", "space", "extraterrestrial"]),
        EmojiItem("👾", ["alien monster", "space invader", "game", "retro"]),
        EmojiItem("🤖", ["robot", "bot", "machine", "tech"]),
        // Hands and gestures
        EmojiItem("👍", ["thumbs up", "like", "approve", "good", "yes"]),
        EmojiItem("👎", ["thumbs down", "dislike", "no", "bad"]),
        EmojiItem("👌", ["ok hand", "perfect", "okay", "pinch"]),
        EmojiItem("🤌", ["pinched fingers", "italian", "chef's kiss"]),
        EmojiItem("🤏", ["pinching hand", "small", "little"]),
        EmojiItem("✌️", ["victory", "peace", "two", "v sign"]),
        EmojiItem("🤞", ["crossed fingers", "luck", "hope", "wish"]),
        EmojiItem("🫰", ["hand with finger through ring", "snap"]),
        EmojiItem("🤟", ["love you gesture", "ily", "rock on"]),
        EmojiItem("🤘", ["sign of horns", "rock", "metal", "cool"]),
        EmojiItem("🤙", ["call me hand", "shaka", "hang loose"]),
        EmojiItem("👈", ["backhand pointing left", "left", "direction"]),
        EmojiItem("👉", ["backhand pointing right", "right", "direction"]),
        EmojiItem("👆", ["backhand pointing up", "up", "direction"]),
        EmojiItem("🖕", ["middle finger", "rude", "offensive"]),
        EmojiItem("👇", ["backhand pointing down", "down", "direction"]),
        EmojiItem("☝️", ["index pointing up", "one", "point"]),
        EmojiItem("🫵", ["index pointing at you", "you", "pointing"]),
        EmojiItem("👋", ["waving", "hello", "goodbye", "hi", "bye"]),
        EmojiItem("🤚", ["raised back hand", "stop", "halt"]),
        EmojiItem("🖐️", ["hand splayed", "stop", "five", "palm"]),
        EmojiItem("✋", ["raised hand", "stop", "high five", "five"]),
        EmojiItem("🖖", ["vulcan salute", "spock", "live long"]),
        EmojiItem("🫱", ["rightward hand", "right"]),
        EmojiItem("🫲", ["leftward hand", "left"]),
        EmojiItem("🫳", ["palm down", "down"]),
        EmojiItem("🫴", ["palm up", "up", "offer"]),
        EmojiItem("🫶", ["heart hands", "love", "hearts"]),
        EmojiItem("👏", ["clapping", "applause", "bravo", "clap"]),
        EmojiItem("🙌", ["raising hands", "celebrate", "hooray", "yay"]),
        EmojiItem("🤲", ["palms together", "offer", "pray"]),
        EmojiItem("🤝", ["handshake", "deal", "agreement", "shake"]),
        EmojiItem("🙏", ["folded hands", "pray", "please", "thanks", "namaste"]),
        EmojiItem("✍️", ["writing", "pen", "author", "sign"]),
        EmojiItem("💅", ["nail polish", "sassy", "nails", "manicure"]),
        EmojiItem("🤳", ["selfie", "phone", "camera"]),
        EmojiItem("💪", ["flexed biceps", "strong", "muscle", "strength"]),
        EmojiItem("🦾", ["mechanical arm", "prosthetic", "cyborg"]),
        EmojiItem("🦿", ["mechanical leg", "prosthetic", "cyborg"]),
        EmojiItem("🦵", ["leg", "kick", "limb"]),
        EmojiItem("🦶", ["foot", "kick", "barefoot"]),
        EmojiItem("👂", ["ear", "listen", "hearing"]),
        EmojiItem("🦻", ["ear with hearing aid", "deaf", "hearing loss"]),
        EmojiItem("👃", ["nose", "smell", "sniff"]),
        EmojiItem("🫀", ["anatomical heart", "heart", "organ"]),
        EmojiItem("🫁", ["lungs", "breathe", "organ"]),
        EmojiItem("🧠", ["brain", "smart", "think", "mind"]),
        EmojiItem("🦷", ["tooth", "dentist", "teeth"]),
        EmojiItem("🦴", ["bone", "skeleton"]),
        EmojiItem("👀", ["eyes", "look", "watching", "see"]),
        EmojiItem("👁️", ["eye", "look", "stare"]),
        EmojiItem("👅", ["tongue", "lick", "taste"]),
        EmojiItem("👄", ["lips", "mouth", "kiss"]),
        EmojiItem("🫦", ["biting lip", "seductive", "nervous"]),
        EmojiItem("💋", ["kiss mark", "lips", "smooch"]),
        EmojiItem("💘", ["heart arrow", "love", "cupid"]),
        EmojiItem("❤️", ["red heart", "love", "heart", "romance"]),
        EmojiItem("🧡", ["orange heart", "love", "heart"]),
        EmojiItem("💛", ["yellow heart", "love", "heart", "friendship"]),
        EmojiItem("💚", ["green heart", "love", "heart", "nature"]),
        EmojiItem("💙", ["blue heart", "love", "heart"]),
        EmojiItem("🩵", ["light blue heart", "love", "heart"]),
        EmojiItem("💜", ["purple heart", "love", "heart"]),
        EmojiItem("🖤", ["black heart", "dark", "heart", "evil"]),
        EmojiItem("🩶", ["grey heart", "heart"]),
        EmojiItem("🤍", ["white heart", "pure", "heart"]),
        EmojiItem("🤎", ["brown heart", "heart"]),
        EmojiItem("💔", ["broken heart", "sad", "heartbreak"]),
        EmojiItem("❤️‍🔥", ["heart on fire", "love", "passion"]),
        EmojiItem("❤️‍🩹", ["mending heart", "heal", "recovery"]),
        EmojiItem("💕", ["two hearts", "love", "romance"]),
        EmojiItem("💞", ["revolving hearts", "love", "spinning"]),
        EmojiItem("💓", ["beating heart", "love", "pulse"]),
        EmojiItem("💗", ["growing heart", "love", "pink"]),
        EmojiItem("💖", ["sparkling heart", "love", "glitter"]),
        EmojiItem("💝", ["heart ribbon", "gift", "love"]),
        EmojiItem("💟", ["heart decoration", "love", "heart"]),
        EmojiItem("☮️", ["peace", "pacifism"]),
        EmojiItem("✝️", ["cross", "christian", "church"]),
    ]

    // MARK: - Animals & Nature (~40)
    static let animals: [EmojiItem] = [
        EmojiItem("🐶", ["dog", "puppy", "pet"]),
        EmojiItem("🐱", ["cat", "kitten", "pet"]),
        EmojiItem("🐭", ["mouse", "rat", "rodent"]),
        EmojiItem("🐹", ["hamster", "pet", "rodent"]),
        EmojiItem("🐰", ["rabbit", "bunny", "easter"]),
        EmojiItem("🦊", ["fox", "cunning", "sly"]),
        EmojiItem("🐻", ["bear", "brown bear", "animal"]),
        EmojiItem("🐼", ["panda", "china", "bear"]),
        EmojiItem("🐻‍❄️", ["polar bear", "arctic", "white bear"]),
        EmojiItem("🐨", ["koala", "australia", "marsupial"]),
        EmojiItem("🐯", ["tiger", "big cat", "stripe"]),
        EmojiItem("🦁", ["lion", "king", "roar"]),
        EmojiItem("🐮", ["cow", "moo", "farm"]),
        EmojiItem("🐷", ["pig", "oink", "farm"]),
        EmojiItem("🐸", ["frog", "leap", "green"]),
        EmojiItem("🐵", ["monkey", "ape", "primate"]),
        EmojiItem("🙈", ["see no evil", "monkey", "hide"]),
        EmojiItem("🙉", ["hear no evil", "monkey", "deaf"]),
        EmojiItem("🙊", ["speak no evil", "monkey", "quiet"]),
        EmojiItem("🐔", ["chicken", "cluck", "farm", "hen"]),
        EmojiItem("🐧", ["penguin", "cold", "arctic"]),
        EmojiItem("🐦", ["bird", "tweet", "fly"]),
        EmojiItem("🦆", ["duck", "quack", "pond"]),
        EmojiItem("🦅", ["eagle", "majestic", "bird"]),
        EmojiItem("🦉", ["owl", "wise", "night"]),
        EmojiItem("🦇", ["bat", "night", "vampire"]),
        EmojiItem("🐺", ["wolf", "howl", "wild"]),
        EmojiItem("🐗", ["boar", "wild pig", "tusks"]),
        EmojiItem("🐴", ["horse", "equine", "neigh"]),
        EmojiItem("🦄", ["unicorn", "magic", "rainbow", "fantasy"]),
        EmojiItem("🐝", ["bee", "honey", "sting", "buzz"]),
        EmojiItem("🐛", ["bug", "caterpillar", "insect"]),
        EmojiItem("🦋", ["butterfly", "beautiful", "transform"]),
        EmojiItem("🐌", ["snail", "slow", "shell"]),
        EmojiItem("🐢", ["turtle", "slow", "shell"]),
        EmojiItem("🐍", ["snake", "reptile", "slither"]),
        EmojiItem("🦎", ["lizard", "reptile", "gecko"]),
        EmojiItem("🦖", ["t-rex", "dinosaur", "dino"]),
        EmojiItem("🐳", ["whale", "ocean", "big"]),
        EmojiItem("🌸", ["cherry blossom", "flower", "pink", "spring"]),
        EmojiItem("🌺", ["hibiscus", "flower", "tropical"]),
        EmojiItem("🌻", ["sunflower", "yellow", "sun", "flower"]),
        EmojiItem("🌹", ["rose", "flower", "red", "love"]),
        EmojiItem("🍀", ["four leaf clover", "luck", "lucky", "ireland"]),
        EmojiItem("🌈", ["rainbow", "colorful", "weather"]),
        EmojiItem("🌊", ["wave", "ocean", "surf", "water"]),
        EmojiItem("⭐", ["star", "favorite", "shine", "gold"]),
        EmojiItem("🌙", ["crescent moon", "night", "lunar"]),
        EmojiItem("☀️", ["sun", "sunny", "day", "bright"]),
        EmojiItem("🔥", ["fire", "hot", "flame", "lit"]),
    ]

    // MARK: - Food & Drink (~27)
    static let food: [EmojiItem] = [
        EmojiItem("🍎", ["apple", "red apple", "fruit"]),
        EmojiItem("🍊", ["orange", "tangerine", "fruit"]),
        EmojiItem("🍋", ["lemon", "citrus", "sour", "fruit"]),
        EmojiItem("🍇", ["grapes", "wine", "fruit"]),
        EmojiItem("🍓", ["strawberry", "red", "fruit"]),
        EmojiItem("🍒", ["cherries", "red", "fruit"]),
        EmojiItem("🍑", ["peach", "fruit", "butt"]),
        EmojiItem("🍍", ["pineapple", "tropical", "fruit"]),
        EmojiItem("🥥", ["coconut", "tropical", "summer"]),
        EmojiItem("🥑", ["avocado", "healthy", "guac"]),
        EmojiItem("🍕", ["pizza", "slice", "italian", "food"]),
        EmojiItem("🍔", ["burger", "hamburger", "fast food"]),
        EmojiItem("🍟", ["fries", "french fries", "fast food"]),
        EmojiItem("🌮", ["taco", "mexican", "food"]),
        EmojiItem("🌯", ["burrito", "wrap", "mexican", "food"]),
        EmojiItem("🍜", ["noodles", "ramen", "asian", "food"]),
        EmojiItem("🍣", ["sushi", "japanese", "fish", "food"]),
        EmojiItem("🍩", ["doughnut", "donut", "sweet", "dessert"]),
        EmojiItem("🍪", ["cookie", "sweet", "biscuit", "dessert"]),
        EmojiItem("🎂", ["birthday cake", "cake", "celebration"]),
        EmojiItem("🍰", ["shortcake", "cake", "slice", "dessert"]),
        EmojiItem("🍫", ["chocolate", "candy", "sweet"]),
        EmojiItem("🍿", ["popcorn", "movie", "snack"]),
        EmojiItem("☕", ["coffee", "hot drink", "cafe", "morning"]),
        EmojiItem("🍵", ["tea", "hot drink", "green tea"]),
        EmojiItem("🧃", ["juice box", "drink"]),
        EmojiItem("🍺", ["beer", "cheers", "drink", "bar"]),
        EmojiItem("🍷", ["wine", "drink", "glass", "red"]),
        EmojiItem("🥂", ["clinking glasses", "toast", "celebrate", "cheers"]),
        EmojiItem("🧁", ["cupcake", "sweet", "dessert", "cake"]),
    ]

    // MARK: - Travel & Places (~21)
    static let travel: [EmojiItem] = [
        EmojiItem("🚗", ["car", "drive", "vehicle", "red"]),
        EmojiItem("🚕", ["taxi", "cab", "yellow", "transport"]),
        EmojiItem("🚙", ["suv", "car", "vehicle"]),
        EmojiItem("🚌", ["bus", "public transport", "school"]),
        EmojiItem("🚎", ["trolleybus", "tram", "transport"]),
        EmojiItem("🏎️", ["racing car", "speed", "formula 1"]),
        EmojiItem("🚑", ["ambulance", "emergency", "medical"]),
        EmojiItem("🚒", ["fire truck", "emergency", "fire"]),
        EmojiItem("✈️", ["airplane", "plane", "fly", "travel", "flight"]),
        EmojiItem("🚀", ["rocket", "space", "launch", "fast"]),
        EmojiItem("🛸", ["ufo", "flying saucer", "alien", "space"]),
        EmojiItem("🚢", ["ship", "cruise", "boat", "ocean"]),
        EmojiItem("⛵", ["sailboat", "sailing", "boat"]),
        EmojiItem("🏖️", ["beach", "summer", "vacation", "sun"]),
        EmojiItem("🏔️", ["mountain", "snow", "peak", "hiking"]),
        EmojiItem("🌆", ["city at dusk", "cityscape", "skyline"]),
        EmojiItem("🌉", ["bridge at night", "bridge", "city", "night"]),
        EmojiItem("🗼", ["eiffel tower", "paris", "france", "travel"]),
        EmojiItem("🗽", ["statue of liberty", "new york", "usa"]),
        EmojiItem("🏰", ["castle", "medieval", "fantasy"]),
        EmojiItem("🌍", ["earth africa", "globe", "world", "earth"]),
        EmojiItem("🌎", ["earth americas", "globe", "world", "earth"]),
        EmojiItem("🌏", ["earth asia", "globe", "world", "earth"]),
    ]

    // MARK: - Activities (~18)
    static let activities: [EmojiItem] = [
        EmojiItem("⚽", ["soccer", "football", "sport", "ball"]),
        EmojiItem("🏀", ["basketball", "sport", "ball", "hoop"]),
        EmojiItem("🏈", ["american football", "sport", "nfl"]),
        EmojiItem("⚾", ["baseball", "sport", "ball"]),
        EmojiItem("🎾", ["tennis", "sport", "racket", "ball"]),
        EmojiItem("🏐", ["volleyball", "sport", "ball"]),
        EmojiItem("🏉", ["rugby", "sport", "ball"]),
        EmojiItem("🎱", ["billiards", "pool", "8 ball", "snooker"]),
        EmojiItem("🏓", ["ping pong", "table tennis", "sport"]),
        EmojiItem("🎯", ["bullseye", "target", "direct hit", "accuracy"]),
        EmojiItem("🎮", ["video game", "controller", "gaming", "gamer"]),
        EmojiItem("🎲", ["dice", "random", "game", "gambling"]),
        EmojiItem("♟️", ["chess", "strategy", "game"]),
        EmojiItem("🎸", ["guitar", "music", "rock", "instrument"]),
        EmojiItem("🎹", ["piano", "music", "keyboard", "instrument"]),
        EmojiItem("🎭", ["performing arts", "theater", "drama", "masks"]),
        EmojiItem("🎨", ["art", "palette", "paint", "creative"]),
        EmojiItem("🎬", ["clapper", "movie", "film", "action"]),
        EmojiItem("🎤", ["microphone", "sing", "music", "karaoke"]),
        EmojiItem("🎧", ["headphones", "music", "listen", "audio"]),
    ]

    // MARK: - Objects (~18)
    static let objects: [EmojiItem] = [
        EmojiItem("💻", ["laptop", "computer", "tech", "work"]),
        EmojiItem("🖥️", ["desktop", "computer", "monitor", "screen"]),
        EmojiItem("📱", ["phone", "mobile", "smartphone", "iphone"]),
        EmojiItem("⌨️", ["keyboard", "type", "computer"]),
        EmojiItem("🖱️", ["mouse", "computer", "click"]),
        EmojiItem("📷", ["camera", "photo", "picture"]),
        EmojiItem("📸", ["camera flash", "selfie", "photo"]),
        EmojiItem("📺", ["television", "tv", "watch"]),
        EmojiItem("📻", ["radio", "music", "broadcast"]),
        EmojiItem("🔋", ["battery", "power", "charge"]),
        EmojiItem("💡", ["lightbulb", "idea", "bright", "smart"]),
        EmojiItem("🔦", ["flashlight", "torch", "light"]),
        EmojiItem("🔑", ["key", "lock", "access", "security"]),
        EmojiItem("🔒", ["locked", "secure", "private"]),
        EmojiItem("🔓", ["unlocked", "open", "accessible"]),
        EmojiItem("📦", ["package", "box", "delivery", "ship"]),
        EmojiItem("📬", ["mailbox", "mail", "letter", "inbox"]),
        EmojiItem("📎", ["paperclip", "attach", "clip"]),
        EmojiItem("✂️", ["scissors", "cut", "craft"]),
        EmojiItem("🧲", ["magnet", "attract", "pull"]),
        EmojiItem("🧪", ["test tube", "science", "experiment", "lab"]),
        EmojiItem("🔬", ["microscope", "science", "biology", "lab"]),
        EmojiItem("🔭", ["telescope", "astronomy", "space", "stars"]),
        EmojiItem("💊", ["pill", "medicine", "drug", "tablet"]),
        EmojiItem("🩺", ["stethoscope", "doctor", "medical"]),
        EmojiItem("🛒", ["shopping cart", "cart", "buy", "shopping"]),
        EmojiItem("🪑", ["chair", "seat", "furniture"]),
        EmojiItem("🚪", ["door", "enter", "exit", "room"]),
        EmojiItem("🪞", ["mirror", "reflection", "vanity"]),
        EmojiItem("🛋️", ["couch", "sofa", "furniture", "relax"]),
    ]

    // MARK: - Symbols (~24)
    static let symbols: [EmojiItem] = [
        EmojiItem("💯", ["100", "perfect", "score", "fire"]),
        EmojiItem("🔥", ["fire", "hot", "flame", "lit", "trending"]),
        EmojiItem("✨", ["sparkles", "glitter", "magic", "shine"]),
        EmojiItem("⭐", ["star", "favorite", "rating", "gold"]),
        EmojiItem("🌟", ["glowing star", "shine", "special"]),
        EmojiItem("💫", ["dizzy", "stars", "spin"]),
        EmojiItem("⚡", ["lightning", "electric", "bolt", "fast", "thunder"]),
        EmojiItem("🎉", ["party", "celebrate", "confetti", "tada"]),
        EmojiItem("🎊", ["confetti ball", "party", "celebrate"]),
        EmojiItem("🎈", ["balloon", "party", "birthday"]),
        EmojiItem("✅", ["check", "done", "yes", "tick", "ok", "complete"]),
        EmojiItem("❌", ["cross", "no", "wrong", "x", "cancel"]),
        EmojiItem("❓", ["question", "what", "huh", "ask"]),
        EmojiItem("❗", ["exclamation", "important", "alert", "warning"]),
        EmojiItem("⚠️", ["warning", "caution", "alert", "danger"]),
        EmojiItem("🚨", ["siren", "alert", "emergency", "police"]),
        EmojiItem("🔴", ["red circle", "red", "stop", "dot"]),
        EmojiItem("🟠", ["orange circle", "orange", "dot"]),
        EmojiItem("🟡", ["yellow circle", "yellow", "dot"]),
        EmojiItem("🟢", ["green circle", "green", "go", "dot"]),
        EmojiItem("🔵", ["blue circle", "blue", "dot"]),
        EmojiItem("🟣", ["purple circle", "purple", "dot"]),
        EmojiItem("⚫", ["black circle", "black", "dot"]),
        EmojiItem("⚪", ["white circle", "white", "dot"]),
        EmojiItem("🏳️", ["white flag", "surrender", "peace"]),
        EmojiItem("🏴", ["black flag", "dark", "pirate"]),
        EmojiItem("♻️", ["recycle", "green", "environment", "reuse"]),
        EmojiItem("🔁", ["repeat", "loop", "refresh", "cycle"]),
        EmojiItem("🔛", ["on", "active", "enabled"]),
        EmojiItem("🆕", ["new", "fresh", "recent"]),
        EmojiItem("🆒", ["cool", "ok", "nice"]),
        EmojiItem("🆓", ["free", "no cost"]),
        EmojiItem("💤", ["zzz", "sleep", "tired", "bored"]),
        EmojiItem("💬", ["speech bubble", "chat", "comment", "talk"]),
        EmojiItem("💭", ["thought bubble", "thinking", "dreaming"]),
    ]

    // MARK: - Flags (~19)
    static let flags: [EmojiItem] = [
        EmojiItem("🏁", ["checkered flag", "racing", "finish", "goal"]),
        EmojiItem("🚩", ["triangular flag", "red flag", "warning", "mark"]),
        EmojiItem("🏳️", ["white flag", "surrender", "peace"]),
        EmojiItem("🏴", ["black flag", "dark", "pirate"]),
        EmojiItem("🏴‍☠️", ["pirate flag", "jolly roger", "pirate"]),
        EmojiItem("🇺🇸", ["us", "usa", "united states", "america"]),
        EmojiItem("🇬🇧", ["uk", "england", "britain", "united kingdom"]),
        EmojiItem("🇨🇦", ["canada", "canadian", "maple leaf"]),
        EmojiItem("🇦🇺", ["australia", "australian", "oz"]),
        EmojiItem("🇩🇪", ["germany", "german", "deutschland"]),
        EmojiItem("🇫🇷", ["france", "french", "paris"]),
        EmojiItem("🇯🇵", ["japan", "japanese", "nippon"]),
        EmojiItem("🇰🇷", ["korea", "korean", "south korea"]),
        EmojiItem("🇨🇳", ["china", "chinese"]),
        EmojiItem("🇧🇷", ["brazil", "brazilian"]),
        EmojiItem("🇮🇳", ["india", "indian"]),
        EmojiItem("🇲🇽", ["mexico", "mexican"]),
        EmojiItem("🇮🇹", ["italy", "italian"]),
        EmojiItem("🇪🇸", ["spain", "spanish"]),
        EmojiItem("🇸🇪", ["sweden", "swedish"]),
        EmojiItem("🇳🇴", ["norway", "norwegian"]),
        EmojiItem("🇫🇮", ["finland", "finnish"]),
        EmojiItem("🇳🇱", ["netherlands", "dutch", "holland"]),
        EmojiItem("🇵🇱", ["poland", "polish"]),
        EmojiItem("🇺🇦", ["ukraine", "ukrainian"]),
    ]
}
